splunk/splunk-connect-for-syslog

- docs/configuration.md
- docs/gettingstarted.md
- docs/gettingstarted/docker-swarm-general.md
- docs/gettingstarted/docker-swarm-rhel7.md
- docs/gettingstarted/docker-systemd-general.md
- docs/gettingstarted/podman-systemd-general.md
Substantial update to the "gettingstarted" series of docs:
1. Warning about matching volume spec in yml/unit files with what is present in the local fs
2. Align individual steps between all four runtime docs
3. Added HEC WORKERS environment variable and instructions
4. Added note to warn admins of default secure operation (SC4S_DEST_SPLUNK_HEC_TLS_VERIFY)
5. Added separate Start, Stop, and Restart guidance 
6. Added a "Verify Proper Operation" section to all four runtime docs
Not included:  Troubleshooting section 
Not Included:  Local filter creation
> Docs gettingstarted update

- docs/configuration.md
- package/etc/conf.d/conflib/_common/compliance_meta.conf
- package/etc/conf.d/log_paths/p_rfc3164-cisco_asa.conf.tmpl
- package/etc/conf.d/log_paths/p_rfc3164-cisco_ios.conf.tmpl
- package/etc/conf.d/log_paths/p_rfc3164-cisco_nx-os.conf.tmpl
- package/etc/conf.d/log_paths/p_rfc3164-fortinet_fortios.conf.tmpl
- package/etc/conf.d/log_paths/p_rfc3164-juniper_idp.conf.tmpl
- package/etc/conf.d/log_paths/p_rfc3164-juniper_junos.conf.tmpl
- package/etc/conf.d/log_paths/p_rfc3164-juniper_netscreen.conf.tmpl
- package/etc/conf.d/log_paths/p_rfc3164-juniper_nsm.conf.tmpl
- package/etc/conf.d/log_paths/p_rfc3164-juniper_nsm_idp.conf.tmpl
- package/etc/conf.d/log_paths/p_rfc3164-paloalto_panos.conf.tmpl
- package/etc/conf.d/log_paths/p_rfc3164-proofpoint_pps_filter.conf.tmpl
- package/etc/conf.d/log_paths/p_rfc3164-proofpoint_pps_sendmail.conf.tmpl
- package/etc/conf.d/log_paths/p_rfc3164_microfocus_arcsight.conf.tmpl
- package/etc/conf.d/log_paths/p_rfc5424_noversion-cisco_asa.conf.tmpl
- package/etc/conf.d/log_paths/p_rfc_5424_noversion-symantec_proxy.conf.tmpl
- package/etc/conf.d/log_paths/p_rfc_5424_strict-juniper_junos.conf.tmpl
- package/etc/context-local/compliance_meta_by_source.conf
- package/etc/context-local/compliance_meta_by_source.csv
This PR will add support using a new add-context parser that will allow a admin to add Splunk meta data (indexed fields) OR change index,source, or source type.
> Setup meta data for compliance needs by filter after source type

- package/etc/conf.d/destinations/splunk_hec.conf.tmpl
- package/etc/conf.d/destinations/splunk_hec_internal.conf.tmpl
- package/etc/conf.d/destinations/splunk_hec_metrics.conf.tmpl
- Set worker count to 10 for internal and metrics destinations
- Set Persist Name for internal to ensure data will be routed to secondary URLS when using internal load balancing.
> Updates to HEC output

- docs/gettingstarted/docker-systemd-general.md
- docs/gettingstarted/podman-systemd-general.md
-dependabot reverted syslog-ng to downlevel 3.23.1 resolving
-docs incorrectly references the sc4s rather than scs docker registry
> Fix release issues

- README.md
- docs/configuration.md
- docs/gettingstarted/byoe-rhel7.md
- docs/gettingstarted/docker-swarm-general.md
- docs/gettingstarted/docker-swarm-rhel7.md
- docs/gettingstarted/docker-systemd-general.md
- docs/gettingstarted/podman-systemd-general.md
- docs/index.md
This change makes the location of env_file consistent however this is a procedural breaking change a deployment using the earlier docs will have the file in the wrong place. Users should move the file from opt/sc4s/default/env_file to opt/sc4s/env_file and revise the sc4s.service file to correct
> Update docs for env_file in getting started

- docker-compose-ci.yml
- tests/Dockerfile
- tests/entrypoint.sh
- tests/pytest.ini
- tests/requirements.txt
- tests/test_ubiquiti_unifi.py
Due to container network occasionally a test will fail that will work on retry this change adds flaky support with minimum 1 max 3 and improves test run time by adding pytest-parallel
> Improve CI performance and reliability

- package/etc/conf.d/log_paths/internal.conf.tmpl
- package/etc/conf.d/log_paths/startup.conf.tmpl
- package/etc/conf.d/sources/startup.conf
- package/etc/context_templates/compliance_meta_by_source.conf
- package/etc/context_templates/vendor_product_by_source.conf
- package/etc/syslog-ng.conf
- package/sbin/entrypoint.sh
- tests/test_common.py
Log previously silent startup config errors as sc4s:events:startup:err and sc4s:events:startup:out.
Bump syslog-ng config to 3.25.1
remove version string from templates no longer required
add tests to ensure version is bumbed in the future
> Multiple startup fixes

- package/etc/conf.d/log_paths/p_zz_fallback.conf.tmpl
- tests/test_common.py
resolve unexpected behaior with syslog-ng out of order processing of directives impacting the hec format for json fallback due to archive support. Add test condition to ensure this doesn't break again
> json events not formatted in fallback

- package/Dockerfile
- package/etc/conf.d/conflib/_common/syslog_format.conf
- package/etc/conf.d/conflib/_common/templates.conf
- package/etc/conf.d/filters/paloalto/panos.conf
- package/etc/conf.d/log_paths/p_zz_fallback.conf.tmpl
- package/etc/go_templates/source_network.t
* Update JSON templates for simplicity and reduced archive disk space
* Remove RAWMSG from 3164 JSON template in preparation for complete removal
* Rename t_JSON to t_JSON_3164 to match that of 5424
* Rename the syslog format rfc5424_bsdtime to rfc3164_version to reflect it is actually RFC3164 with an extra "version"  string appended rather than RFC5424 with a BSD timestamp
* Unrelated -- fix Dockerfile to include the "-y" flag on Devlopment Tools installation
> Update templates and syslog formats

- package/etc/conf.d/log_paths/p_rfc3164-forcepoint_webprotect.conf.tmpl
- package/etc/conf.d/log_paths/p_rfc3164-symantec_brightmail.conf.tmpl
- package/etc/conf.d/log_paths/p_rfc3164-ubiquiti_unifi.conf.tmpl
- package/etc/conf.d/log_paths/p_vmware_vsphere.conf.tmpl
- package/etc/conf.d/log_paths/p_zz_fallback.conf.tmpl
- tests/test_common.py
* Provide more granular `sc4s_vendor_product` values to help distinguish the actual log path used.
* Results in far cleaner archive files on disk
> Update sc4s_vendor_product values

- docs/gettingstarted/byoe-rhel7.md
- docs/gettingstarted/docker-swarm-general.md
- docs/gettingstarted/docker-swarm-rhel7.md
- docs/gettingstarted/docker-systemd-general.md
- docs/gettingstarted/podman-systemd-general.md
* Remove extra spaces at end of sentences; affects md rendering
* Remove extra blank lines from Unit file examples for readability
* Update all version strings to 3.25.1
* Remove extra "Scale Out" section from runtime docs (covered elsewhere)
> Markdown and formatting update

- package/etc/conf.d/log_paths/p_rfc3164-paloalto_panos.conf.tmpl
* Change output template from `t_hdr_msg` to `t_msg_only` for Palo Alto log path to account for removed "unset" config element
> Fix output template for Palo Alto log path

- docker-compose.yml
- docs/configuration.md
- package/etc/conf.d/conflib/_common/templates.conf
- package/etc/go_templates/source_network.t
* Add an environment variable `SC4S_SOURCE_STORE_RAWMSG` to enable the collection/storage of the "on the wire" message for use in the 3164 fallback template.
* Useful for development and debugging of log paths and filters.  NOT FOR USE IN PRODUCTION due to memory/disk overhead.
> Add RAWMSG storage for debugging

- docs/gettingstarted/docker-swarm-general.md
- docs/gettingstarted/docker-swarm-rhel7.md
- docs/gettingstarted/docker-systemd-general.md
- docs/gettingstarted/podman-systemd-general.md
- docs/sources/CommonEventFormat/index.md
* Simplify runtime docs by removing entire unit/compose files and replacing with snippets
* Clarify CEF documentation
* typos/grammar/flow fixes
> Simplify runtime docs

- tests/conftest.py
* Update docker-compose port range from 5000-5006 to 5000-5007 to account for pfsense tests on port 5006.  Will get a "key error" if range stops at 5006.
> Update docker port range to 5000-5007

- package/etc/conf.d/filters/cisco/meraki.conf
- package/etc/conf.d/log_paths/lp-common_event_format.conf.tmpl
* Add the guess-timezone() flag to log paths that parse epoch timestamps.  Though epoch is timezone-free, it can be set incorrectly by the sending device and/or test tools.
> Add guess-timezone() to sources with epoch timestamps

- package/etc/conf.d/log_paths/lp-sc4s_startup.conf.tmpl
* Fix sourcetype/key reversal in startup log path
> Startup log path `splunk_indexes.conf` fix

- package/etc/conf.d/log_paths/lp-sc4s_startup.conf.tmpl
When a non-main index was selected for sc4s:events this subtype was not routed due to a typo
> Correct vendor_product key for syslog-ng std output

- package/etc/conf.d/destinations/splunk_hec_internal.conf.tmpl
* Update batch timeout on the `d_hec_internal` destination from 1ms to 1000ms to more closely align to the regular `d_hec` destination
> Update internal log batch timeout

- package/etc/conf.d/log_paths/lp-juniper_junos.conf.tmpl
- package/etc/conf.d/log_paths/lp-juniper_junos_structured.conf.tmpl
* Currently, the Juniper add-on is indexing the RT_IDS events to juniper:junos:firewall sourcetype and SC4S is indexing the same events to juniper:junos:idp sourcetype. Hence, modified the sourcetype for RT_IDS events to make it consistent with the add-on.
> Changed sourcetype of RT_IDS events of Juniper to juniper:junos:firewall

- package/etc/go_templates/source_network.t
* Add the `store_raw_message` flag (controlled by the env var `SC4S_SOURCE_STORE_RAWMSG`) to the sources rather than the parsers in `source_network.t`. This will allow RAWMSG to be set for all sources (previously it was just 3164 and a few others)
> Update raw message support for all traffic

- package/etc/conf.d/conflib/_common/date-parser_nofilter.conf.tmpl
- package/etc/conf.d/filters/cisco/cisco_syslog.conf
- package/etc/conf.d/filters/cisco/meraki.conf
- package/etc/conf.d/filters/cisco/ucm.conf
- package/etc/conf.d/filters/citrix/netscaler.conf.tmpl
- package/etc/conf.d/log_paths/lp-checkpoint_splunk.conf.tmpl
- package/etc/conf.d/log_paths/lp-cisco_acs.conf.tmpl
- package/etc/conf.d/log_paths/lp-cisco_ise.conf.tmpl
- package/etc/conf.d/log_paths/lp-common_event_format.conf.tmpl
- package/etc/conf.d/log_paths/lp-fortinet.conf.tmpl
- package/etc/conf.d/log_paths/lp-paloalto_panos.conf.tmpl
- package/etc/conf.d/log_paths/lp-zscaler_lss.conf.tmpl
- package/etc/conf.d/log_paths/lp-zscaler_nss.conf.tmpl
- tests/test_cisco_acs.py
- tests/test_cisco_ise.py
* Add date-parser() functionality that does not filter, so that an alternate path can be taken in case of a missed parse.  This is useful to avoid message drops when unique ports are used and standard filtering mechanisms are bypassed.
* Useful for rogue event detection, particularly in multi-event sources such as Cisco ISE and ACS
> Add non-filtering date-parser() option

- package/etc/conf.d/filters/checkpoint/splunk.conf
- package/etc/conf.d/log_paths/lp-checkpoint_splunk.conf.tmpl
- tests/docker-compose.yml
- tests/test_checkpoint.py
This will unwrap the proper OS syslog event from the header when origin is the logger OS however it will not support third party relay via checkpoint in this format.
> Support OS syslog nested in Checkpoint event format

- package/etc/conf.d/conflib/_common/syslog_format.conf
* Refine 5424 preprocessor to allow all printable ASCII characters for `APPNAME`, `PROCID`, and `MSGID`.
> Fix 5424 preprocessor

- docs/sources/Cisco/index.md
- docs/sources/Zscaler/index.md
- package/etc/conf.d/log_paths/lp-zscaler_lss.conf.tmpl
- package/etc/context_templates/splunk_index.csv.example
- tests/test_zscaler_proxy.py
* Fix incorrect Meraki and Zscaler keys in docs
* Change zscaler LSS `zpa-auth` logs to use `netproxy` index (to match all other LSS events).
> Update metadata keys for Meraki and Zscaler

- docs/gettingstarted/byoe-rhel7.md
- docs/gettingstarted/docker-swarm-general.md
- docs/gettingstarted/docker-swarm-rhel7.md
- docs/gettingstarted/docker-systemd-general.md
- docs/gettingstarted/podman-systemd-general.md
* Document RHEL/podman netfilter table update bug
* Remove `SC4S_DEST_SPLUNK_HEC_WORKERS=6` from documentation (default in code is 10)
> Document netfilter bug

- package/etc/conf.d/conflib/_common/templates.conf
* Update 5424 output templates to include RAWMSG.  Too confusing for most users without it, and there are some small parts of the message that are excluded (such as colons) that are needed to reassemble the raw message with the constituent macros.
> Update 5424 templates to include RAWMSG

- docs/gettingstarted/podman-systemd-general.md
* `ExecStartPost` command requires a space around the semicolon separating the two individual commands.
> Update conntrack unit file entry with required space

- package/etc/conf.d/log_paths/lp-sc4s_internal.conf.tmpl
- tests/test_common.py
* Update `sc4s_internal.conf.tmpl` to update regex to handle new connection statistic in syslog-ng version 3.27
> Fix regex for new statistic in syslog-ng 3.27

- package/etc/conf.d/log_paths/lp-sc4s_internal.conf.tmpl
* Update lookahead in `lp-sc4s_internal.conf.tmpl` to include _either_ a `=` or `,` character in the lookahead for SourceID
> Update lookahead for metrics regex

- docs/configuration.md
* Use ampersand escape for angle brackets
* Break up super-long  lines into multiple lines for editabliity.
> Ampersand escape for angle brackets

- package/etc/conf.d/log_paths/lp-dell_rsa_secureid.conf.tmpl
* Fix `date-parser-nofilter()` template argument (space rather than comma)
> Fix `date-parser()` template

- docs/sources/Checkpoint/index.md
- package/etc/conf.d/log_paths/lp-checkpoint_splunk.conf.tmpl
- tests/test_checkpoint.py
This change uses the virtual blade name from origin sic name or the name of the source firewall from origin sic name rather than the log manager name when available in the event.
> Improve checkpoint host value logic for v firewall systems

- docs/gettingstarted/docker-systemd-general.md
- docs/gettingstarted/podman-systemd-general.md
- package/etc/conf.d/filters/cisco/cisco_syslog.conf
- package/sbin/entrypoint.sh
- When starting up check the pid and exit the container if it is not running on startup failure return the syslog-ng error code to systemd.
- Remove deprecated preflight checks from the systemd unit examples. Existing users can remove or continue these checks with no consequences non breaking
> Improve startup process

- docs/gettingstarted/index.md
* Update prerequisites in docs to indicate that the `em_metrics` index is optional now that metrics is opt-in.
> Update `em_metrics` index creation as optional

- package/etc/conf.d/log_paths/lp-cisco_ise.conf.tmpl
We have changed the template to **t_hdr_msg** from **t_msg_only** of lp-cisco_ise.conf.tmpl file for Cisco ISE add-on as the CIM mapping is defined using **CISE_*** string and we were unable to get that string using **t_msg_only** template as the header part was getting removed.
So to overcome that, we have used **t_hdr_msg** template and we are able to get that string.
Link to JIRA: https://jira.splunk.com/browse/ADDON-26524
> ADDON-26524: Modified log_path file for Cisco ISE

- package/etc/conf.d/log_paths/lp-cisco_ise.conf.tmpl
- tests/test_cisco_ise.py
CISE_Alarm events of Cisco ISE, Do not contain `ISE.num`, `ISE.seq`, etc fields and the format is different than other CISE_* fields. Hence added a check that if the event is CISE_Alarm then index the event as is and do not wait to group it with others.
> Fixed the issue of CISE_Alarm events for Cisco ISE

- semtag
If commit message has a tag [<type>] in the begging of the message it will be used for release notes
where type  consists of “CI" "DOC" "FIX" "FEATURE" "FILTERADD" "FILTERMOD" "REVERT" "TEST"
eg: [TEST] <commit message>
> [FEATURE] Release Notes using commit mesages with [<type>]

- package/etc/conf.d/conflib/_splunk/splunkfields.conf.tmpl
- package/etc/conf.d/log_paths/lp-checkpoint_splunk.conf.tmpl
- package/etc/conf.d/log_paths/lp-paloalto_panos.conf.tmpl
- package/etc/go_templates/splunk_hec.t
* Add host override capability to `compliance_meta_by_source`
* Adjust HOST settings in CHPT and Palo log paths to accommodate this change
* Addresses https://github.com/splunk/splunk-connect-for-syslog/issues/572
> * Add host override for compliance_meta

- docs/troubleshooting.md
* Account for the case where systemd will not issue an immediate error after sc4s service startup
> Clarify initial troubleshooting steps

- package/etc/conf.d/log_paths/lp-common_event_format.conf.tmpl
False error caused when itterating through multiple time stamps
add support for fractional seconds
> [filtermod] CEF time stamp

- package/etc/conf.d/log_paths/lp-cisco_acs.conf.tmpl
ACS more often than not does not send a better time than BSD time field so do not attempt to use it
> [filtermod] Resolve time issue in acs

- package/etc/conf.d/filters/cisco/cisco_syslog.conf
False error reported when cisco device sends uptime
device reported time errors will now use the indexed field cisco_time_error
Add micro seconds format without year
> [filtermod] cisco date parser issues

- package/etc/conf.d/log_paths/lp-dell_rsa_secureid.conf.tmpl
- tests/test_dell_rsa_secureid.py
* Fix time/date parsing in RSA SecurID
* Nit: Should fix all references to this source as `SecurID` (with no "e")
> RSA SecurID timestamps

- package/etc/conf.d/conflib/_common/templates.conf
- package/etc/conf.d/log_paths/lp-common_event_format.conf.tmpl
- package/etc/context_templates/splunk_metadata.csv.example
Change the default CEF and Imperva template to t_legacy_hdr_msg which will include the full header
> [filtermod] cef correct template for imperva securesphere

- package/etc/conf.d/log_paths/lp-dell_rsa_secureid.conf.tmpl
* Fix host parsing in RSA log path to take into account the new `.splunk.host` macro for host output in Splunk `/event` JSON blob
> Fix host parsing in RSA log path

- package/etc/conf.d/conflib/_common/p_vendor_product_by_source.conf
- package/etc/conf.d/sources/rfc5687.conf.tmpl
- package/etc/go_templates/source_network.t
* Remove block function for `vendor_product_by source` parser; simplify calling syntax
* Rename parser file in `_common` to `p_vendor_product_by_source.conf` to align with naming convention
> Simplify `vendor_product_by_source` parser

- package/etc/go_templates/source_network.t
* Change reverse DNS default to "no"
* Reverse DNS can cause unpredictable delay in both UDP and TCP event processing if a high-performance, caching nameserver is not used
> Change reverse DNS default to "no"

- docs/sources/Simple/index.md
- package/etc/conf.d/log_paths/lp-zzw-simple_port.conf.tmpl
- package/etc/context_templates/splunk_metadata.csv.example
- package/sbin/entrypoint.sh
* Refine `SIMPLE` log path to follow traditional `vendor_product` syntax in all config areas
> Refine `SIMPLE` log path

- package/etc/conf.d/log_paths/lp-zzw-simple_port.conf.tmpl
* Update comment to reflect upper case variable name passed to `source_networks.t` and align with convention in regular log paths
> Update comment to reflect upper case

- package/sbin/entrypoint.sh
* Add stanza to `entrypoint.sh` to check for a persist file that references the old root directory for the buffer queue files.  Update to new root if necessary.
* Move `cd $S4S_ETC` to the appropriate place (before gomplate execution)
* Update current directory handling (pushd/popd)
> fix: Correct issue with migrated location for syslog queue files

- docs/gettingstarted/docker-compose-MacOS.md
- docs/gettingstarted/docker-swarm-general.md
- docs/gettingstarted/docker-swarm-rhel7.md
- docs/gettingstarted/docker-systemd-general.md
- docs/gettingstarted/podman-systemd-general.md
* Highlight via `IMPORTANT:` the need to always use the latest and greatest unit/compose file
* Remove obsolete `conntrack` workarround updates
> doc: Important Note to remind users to use the latest unit/compose file

- docs/configuration.md
- docs/sources/Cisco/index.md
* Clarify override operation of `splunk_metadata.csv` and role of `splunk_metadata.csv.example`
* Alphebetize Cisco sources in source doc and expand acronyms
> doc:  Clarify `splunk_metadata.csv` operation; Alphabetize Cisco sources

- package/sbin/entrypoint.sh
Fixed #888 when using a custom CA for http event collector the curl checks should also use that CA
> fix(entrypoint): Use custom CA for curl check

- package/etc/conf.d/log_paths/1/lp-cisco_ucm.conf.tmpl
Resolve this error at startup when an alt dest is enabled
"./conf.d/log_paths/1/lp-cisco_ucm.conf.tmpl" at <regexp>: can't evaluate field ReplucmLiteral in type *funcs.ReFuncs
> fix(cisco_ucm): Search and replace causes invalid log path

- package/etc/conf.d/conflib/_common/syslog_format.conf
- package/etc/conf.d/log_paths/2/lp-juniper_junos.conf.tmpl
- package/etc/patterndb-raw.d/syslog.xml
- package/etc/patterndb.d/juniper/junos.xml
When a 1 version indicator is present on a non 5424 event we strip the 1 to allow the parser to function correctly. Safer handling.
> fix(source): Safer detection of malformed BSD Syslog versioned

- package/etc/conf.d/log_paths/1/lp-aab-syslog-ng_failed-parser.conf.tmpl
- package/etc/patterndb.d/syslog-ng.xml
With certain poor implementation of RFC5424 by source vendors a message may fail to parse with a specific reason rendering the message non-processable. When this occurs uses sourcetype=sc4s:failed as the only solution for these events is a vendor fix.
> feat: When a syslog event fails to parse use new sourcetype

- docs/configuration.md
Clarify location of `SC4S_SOURCE_TLS_ENABLE` in docs
> docs: clarify TLS enable instructions

- package/sbin/entrypoint.sh
When config syntax is invalid handle and exit allowing any runtime error to be handle by the main while loop.
> fix(entrypoint): Improve invalid syntax issues

- package/etc/conf.d/conflib/raw/app-cisco_syslog.conf
In most cases the cisco PRI is meaningless in some newer devices the severity will match the message using the new syslog-ng no parse feature to capture pri
> fix(cisco_syslog): Parse PRI for cisco events

- docs/sources/Splunk/index.md
- package/etc/conf.d/conflib/fallback/app-nix_syslog.conf
- package/etc/conf.d/conflib/raw/app-f5_bigip_syslog.conf
- package/etc/conf.d/conflib/syslog/app-f5_bigip.conf
- package/etc/conf.d/conflib/syslog/app-mark.conf
- package/etc/go_templates/source_network.t
Some syslog sources send -- MARK -- events these mean nearly nothing null_queue by default user can set "SC4S_SOURCE_MARK_MESSAGE_NULLQUEUE" to no to retain these events
> feat(mark): Null queue messages that are marks

- package/etc/conf.d/conflib/syslog/app-symantec_ep.conf
- tests/test_symantec_ep.py
As part of this jira fixed below issue.
Below events is getting assigned into incorrect sourcetype
2021-03-23 04:17:01,Site: My Site,Server Name: C2560767323,Domain Name: Default,Client has downloaded the issued Command,WORKGROUP,Administrator,LocalComputer
Actual Result:
sourcetype=symantec:ep:scm:system:syslog
Expected Result:
sourcetype=symantec:ep:agent:syslog
After this change sourcetype will assign as expected result.
Jira Ref: [ADDON-35667](https://jira.splunk.com/browse/ADDON-35667)
> fix: Updated sc4s filter to fix incorrect souretype assignment issue

- package/etc/conf.d/conflib/syslog/app-cisco_syslog_nix.conf
- tests/test_cisco_asa.py
Cisco FTD 6.1.1 removes " : " before %FTD and replaces with a double space. This makes the format "less" malformed and allowed it to pass as nix:syslog
> fix(cisco_ftd): Support cisco FTD 6.6.1

- package/etc/conf.d/conflib/raw/app-syslog_xml.conf
- package/etc/conf.d/sources/internal.conf
Code was correctly sending event to fallback but also logging 1 error per event to stdout
> fix(xml): When source is XML like but invalid don't stdout error

- package/etc/conf.d/conflib/syslog/app-cisco_syslog_bsd.conf
When cisco FTD is sending mostly compliance (RFC3164) syslog instead of the normally broken cisco_syslog the source type is wrong for IDS events
> fix(cisco_ftd): When cisco FTD wrong source type

- package/etc/conf.d/conflib/net_source/app-nix_syslog.conf
When a product key is arrived via vendor_product_by_source OR by PORT for example vmware_vsphere some data may still be "nix" like syslog. We will now compose a new product key ${.netsource.sc4s_vendor_product}_nix_syslog i.e. vmware_vsphere_nix_syslog allowing index/sourcetype to be overridden in this case. fixes #1176
> feat: allow meta config for nix_syslog by more specific values

- package/etc/conf.d/sc4slib/source_syslog/plugin.jinja
- package/etc/conf.d/sc4slib/source_syslog/plugin.py
fixes #1189
Adds support for a new env var by port id. When addressing noncompliant syslog sources there can be cases where the raw parser required may conflict with a supported raw parser. This feature allows the creation of app-parsers using a custom topic name.
```
SC4S_LISTEN_SIMPLE_FIRST_FIREWALL_UDP=9998
SC4S_LISTEN_SIMPLE_FIRST_FIREWALL_TOPIC=mytopic
```
will produce
```
app-parser(topic(mytopic-raw-syslog)); 
```
> feat(source): Support custom topic sets for extreme snowflakes

- package/etc/conf.d/conflib/raw/app-cisco_syslog.conf
> fix(cisco_syslog): support IOS with extra space in header

- package/sbin/entrypoint.sh
If the hec endpoint doesn't return 200 it failed no need to grep can be a problem with dlp tech.
> fix(entrypoint): HEC test does not need grep

- package/etc/conf.d/conflib/_common/t_templates.conf
This is a tiny improvement I use mainly to see how the contribution process works and also to get to know Github actions which don't run on my fork. I don't insist on merging this, I am just trying to get more familiar with sc4s.
> feat(t_templates): use syslog-ng default substitution instead of $(if)

- package/etc/conf.d/log_paths/2/lp_dest_alts_global/plugin.jinja
Previously "null_queue" fitlers were applied only on the source side which is useful for dropping data with no value to any source. This PR adds support for dropping data from a specific dest in both global and select modes.
> feat: Support destination specific drop

- docs/sources/F5/index.md
- package/etc/conf.d/conflib/syslog/app-syslog-f5_bigip.conf
- tests/test_f5_bigip.py
Added rewrite section to f5 to account for sourcetype `f5:bigip:apm:syslog`. 
Fixes #1423
> feat(f5): Support APM source type

- docs/sources/BeyondTrust/index.md
- mkdocs.yml
- package/etc/conf.d/conflib/_common/t_templates.conf
- package/etc/conf.d/conflib/post-filter/app-postfilter-beyondtrust_sra.conf
- package/etc/conf.d/conflib/post-filter/app-postfilter-cisco_acs.conf
- package/etc/conf.d/conflib/syslog/app-syslog-beyondtrust_sra.conf
- package/etc/conf.d/log_paths/2/lp_dest_alts_global/plugin.jinja
- package/etc/conf.d/log_paths/2/lp_dest_alts_global/plugin.py
- tests/docker-compose.yml
- tests/test_beyondtrust.py
fixes #1422
This PR adds bomgar now known as BeyondTrust Secure Remote access. For the first time format translation is supported in sc4s. Format translation is on by default and will transform the header + kv pair format into json when forwarded to Splunk and into SDATA pairs when forwarded by IETF syslog. BSD syslog will retain the original format.
> feat: Support Beyond Trust BOMGAR

- package/etc/conf.d/conflib/raw/app-raw-cisco_ftd_nopri-bsd.conf
- package/etc/conf.d/conflib/raw/app-raw-cisco_ftd_nopri-iso.conf
- tests/test_cisco_asa.py
Certain cisco devices send a "cisco like" but not correct cisco header and are missing the PRI and header separator. This seems to impact threat defense events only.
> feat: Support invalid FTD events

- package/etc/conf.d/conflib/almost-syslog/app-almost-syslog-arista_eos.conf
- package/etc/conf.d/conflib/almost-syslog/app-almost-syslogz-bsd-onedigitday.conf
When the leading zero/space is missing for BSD.
fixes #1438
> fix: support bsd date

- package/etc/conf.d/conflib/syslog/app-syslog-dell_switch_n.conf
Certain unexpected matches causing incorrect sourcetype
> fix: powerswitch-n greedy filter

- package/etc/conf.d/conflib/_common/t_templates.conf
- package/etc/conf.d/conflib/_splunk/splunkfields.conf
- package/etc/conf.d/conflib/syslog/app-syslog-checkpoint_syslog.conf
- package/etc/conf.d/conflib/syslog/app-syslog-hpe_ilo.conf
- package/etc/conf.d/conflib/syslog/app-syslog-juniper_junos_structured.conf
- package/etc/conf.d/conflib/syslog/app-syslog-polycom_rprm.conf
- package/etc/conf.d/conflib/syslog/app-syslog-tanium.conf
- package/etc/conf.d/sources/internal.conf
- package/etc/local_config/app_parsers/syslog/app-nix_example.conf
Use the compact 5424 template with "-" place holders for host and timestamp to conserve bytes by default
> feat: Use compact 5424 template by default

- package/etc/conf.d/conflib/almost-syslog/app-almost-syslogz-bsd-onedigitday.conf
This parser should only be required for invalid headers with no space or zero padding in day number
> fix: limit one day parser

- package/etc/conf.d/conflib/syslog/app-syslog-stealthbits_stealthintercept_alerts.conf
- package/etc/pylib/parser_stealthbits.py
In default json output the first field name contained the "msg" The first field will now become the words following the final punctuation. [\!\?\.]
> fix: Stealthbits intercept parser

- package/etc/conf.d/conflib/syslog/app-syslog-fortigate_fortiweb.conf
> fix: fortinet events with "ms" in time field but no epoch

- package/etc/conf.d/conflib/syslog/app-syslog-symantec_proxysg.conf
Revert change to symantec from bluecoat to prevent breaking customer deployments
> fix: incorrect vendor for bluecoat

- package/etc/conf.d/conflib/syslog/app-syslog-citrix_netscaler_svm.conf
- tests/test_citrix_netscaler.py
* Updated the filter for Citrix NetScaler Syslog event.
* Updated the filter criteria for `citrix:netscaler:appfw` sourcetype to correctly map the events to the respective sourcetype as below (similar to  [PR #1862](https://github.com/splunk/splunk-connect-for-syslog/pull/1862))
Below is an example of the Syslog event for which the filter has been updated:
<pre><134>Jun 18 18:18:42 svm_service: 1.1.1.1  18/06/2020:16:18:42 GMT mynetscaler2 0-PPE-0 : GUI CMD_EXECUTED : User nsroot - Remote_ip 10.55.1.100 - Command "login login tenant_name=Owner,password=***********,challenge_response=***********,token=1c81504d124245d,client_port=-1,cert_verified=false,sessionid=***********,session_timeout=900,permission=superuser" - Status "Done"</pre>
> fix(citrix_netscaler): updated the filter for syslog events

- package/etc/conf.d/log_paths/0/lp_dest_filtered_alts_select/plugin.jinja
- package/etc/conf.d/log_paths/0/lp_dest_filtered_alts_select/plugin.py
Closes #1897 
The debug mode can be enabled e.g. for cisco_asa messages by setting following property
SC4S_DEST_CISCO_ASA_FILTERED_ALTERNATES=d_hec_debug
SC4S_DEST_CISCO_ASA_ALT_FILTER=f_is_rfc3164
> feat: key fixed and debug mode reinstated

- package/Dockerfile
RHEL8 ubi base image is updated to latest version 8.7-1054
> fix: updating RHEL base image for container

- package/Dockerfile
- package/Dockerfile.lite
- package/sbin/entrypoint.sh
It will fix the CA and TLS certs , as we have changed the base image from RHEL to Alpine , the existing way of updating the certificate was not working.
> fix: ca and tls certificate based on alpine based container

- docs/sources/vendor/CyberArk/pta.md
Incorrect vendor product description in documentation reported: https://github.com/splunk/splunk-connect-for-syslog/issues/2127 .
Key has been updated to match `package/etc/conf.d/conflib/cef/app-cef-cyber_ark_pta.conf` and [vendor documentation](https://docs.cyberark.com/PAS/Latest/en/Content/PTA/CEF-Based-Format-Definition.htm)
> docs: Update CyberArk_PTA vendor product description

- package/etc/conf.d/conflib/almost-syslog/app-almost-syslog-cisco_syslog.conf
- package/etc/conf.d/conflib/syslog/app-syslog-arista_eos.conf
- package/etc/conf.d/conflib/syslog/app-syslog-cisco_syslog.conf
- tests/test_arista.py
- tests/test_cisco_ace.py
In https://github.com/splunk/splunk-connect-for-syslog/issues/2139 it has been reported that some Arista EOS logs are miscategorized as Cisco IOS.
In fact those two vendors use a very similar log format. 
The difference is **Arista** will always contain program name before the first colon:
`Aug 18 03:36:42 AleL3Agent-primary: %AGENT-6-INITIALIZED: Agent 'AleL3Agent-primary' initialized; pid=XXXX`
In **Cisco** there is usually just a timestamp:
`Feb 14 09:40:10.326: %LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet0/1, changed state to up`
Sometimes timestamp with timezone:
`{{ mark }}: {{ year }} {{ bsd }} PDT: %DAEMON-3-SYSTEM_MSG: ftp disabled, removing - xinetd[4930] {{ host }}`
And sometimes also program name, but with all letters uppercase:
`'{{ mark }}{{ bsd }} …
> Fix: fix arista eos miscategorized as cisco ios

- docs/configuration.md
- package/etc/conf.d/conflib/_splunk/fix_dns.conf
- package/etc/conf.d/sources/source_syslog/plugin.jinja
- package/etc/conf.d/sources/source_syslog/plugin.py
- package/etc/pylib/parser_fix_dns.py
- package/lite/etc/conf.d/sources/source_syslog/plugin.jinja
- tests/docker-compose.yml
solves https://github.com/splunk/splunk-connect-for-syslog/issues/2236
default:
`SC4S_USE_REVERSE_DNS=yes`
```
SC4S_USE_REVERSE_DNS=yes
SC4S_REVERSE_DNS_KEEP_FQDN=yes
```
> feat: add FixFQDNResolver

- docs/sources/vendor/Checkpoint/logexporter_5424.md
The formatting as previously given resulted in many of the template tokens surrounded by brackets to be interpreted by the HTML convertor as an HTML tag without a closing pair, leading the convertor dropping it. Adding monospace modifiers fixes this issue.
Additionally, adjust the language for readability, and add some missing links.
> docs/sources/vendor/Checkpoint: Fix formatting

- docs/edge_processor.md
Hi, please take a look at my edits to make sure i did not accidentally misinterpret the meaning of the original text. I'll do another final pass after that.
> docs: review edge processor documentation

- docs/sources/vendor/Broadcom/proxy.md
- package/etc/conf.d/conflib/syslog/app-syslog-symantec_proxysg.conf
- package/lite/etc/addons/broadcom/app-syslog-symantec_proxysg.conf
- tests/test_symantec_proxy.py
solves https://github.com/splunk/splunk-connect-for-syslog/issues/2347
> fix: update Bluecoat sourcetype to match TA 3.8.1

- docs/sources/vendor/Aviatrix/aviatrix.md
- package/etc/conf.d/conflib/syslog/app-syslog-aviatrix.conf
- package/lite/etc/addons/aviatrix/addon_metadata.yaml
- package/lite/etc/addons/aviatrix/app-syslog-aviatrix.conf
- package/lite/etc/config.yaml
- tests/test_aviatrix.py
solves https://github.com/splunk/splunk-connect-for-syslog/issues/2357
> feat: create parser for Aviatrix

- package/etc/conf.d/conflib/almost-syslog/app-almost-syslog-cisco_syslog.conf
- package/lite/etc/addons/cisco/app-almost-syslog-cisco_syslog.conf
- tests/test_cisco_ios.py
fixes https://github.com/splunk/splunk-connect-for-syslog/issues/2247
> fix: fix app-almost-syslog-cisco_syslog

- ansible/resources/docker_sc4s.service
- ansible/resources/podman_sc4s.service
- docs/resources/docker/sc4s.service
- docs/resources/podman/sc4s.service
When a VM or Computer with SC4S shutdown suddently because electrical outage or other problems, SC4S container is not removed, so when you try to start again an error is fired with "Can not create, another container with SC4S name exists!"
Executing this ExecStartPre ensures that if the container exists is deleted. If the container doesn't exist the code || /bin/true makes the script continue.
Issue link: https://github.com/splunk/splunk-connect-for-syslog/issues/2475
@ikheifets-splunk is checking the issue
> Fix for the issue 2475: 

- package/etc/conf.d/conflib/netsource/app-netsource-cisco_esa.conf
- package/lite/etc/addons/cisco/app-netsource-cisco_esa.conf
- tests/test_cisco_esa.py
Jira Ticket: https://splunk.atlassian.net/browse/ADDON-71783
Added support for new log-out events(ESA 15.5.1-onprem).
`<14>Jun 4 15:45:37 ironport.esa.com Info: PID 2585: User admin logged out from session because of inactivity timeout.`
> feat: Support for Cisco ESA 15.5.1 log out events

- package/etc/conf.d/conflib/netsource/app-netsource-cisco_esa.conf
- package/lite/etc/addons/cisco/app-netsource-cisco_esa.conf
- tests/test_cisco_esa.py
Jira_ticket: https://splunk.atlassian.net/browse/ADDON-72562
Added new sourcetype
- cisco:esa:antivirus
Also mapped the following programs into **cisco:esa:system_logs**
- euq_logs
- service_logs
- reportd_logs
- sntpd_logs
- smartlicense
Additionally mapped the updater_logs into **cisco:esa:error_logs**
> feat: add support for new sourcetypes of Cisco ESA TA v1.7.0

- package/etc/conf.d/conflib/_splunk/splunkfields.conf
- package/etc/conf.d/sources/internal.conf
- package/etc/conf.d/sources/source_syslog/plugin.jinja
SC4S already supports the proxy protocol which is useful in some scenarios when using proxies or LBs: https://www.syslog-ng.com/community/b/blog/posts/finding-the-real-source-ip-using-the-proxy-protocol-with-syslog-ng
This PR implements a new overwrite. If `SC4S_SOURCE_PROXYCONNECT=yes`, SC4S will overwrite the HOST value with `PROXIED_SRCIP`.
Before the change:
`host` set to the LB IP
After:
`host` set to the IP of the source
> feat: load host IP from proxied source IP

- charts/splunk-connect-for-syslog/templates/statefulset.yaml
We're running into issues where, after updating our config in the chart, we then need to manually restart the StatefulSet in order for it to get the changes. This PR adds checksum annotations for all three ConfigMaps to the StatefulSet, such that changing the config in any way will automatically trigger a rollout.
> feat: Adds config checksums to Helm chart to trigger rollout on change

- dashboard/dashboard.xml
Credit: @makal27
https://github.com/splunk/splunk-connect-for-syslog/issues/2552
> update SC4S dashboard

- docs/create-parser.md
docs: Updated the dead links on create-parser page
> docs: Updated the dead links on create-parser page

- docs/gettingstarted/byoe-rhel8.md
Updated suggested rhel version from 8.0 to 9.5
As for centos, there is a blog post regarding newer version (9, see https://www.syslog-ng.com/community/b/blog/posts/installing-syslog-ng-on-centos-stream-9) but it's an experimental version, and nothing new appeared about it for 3 years.
> docs: Changed rhel version in docs

- package/etc/conf.d/conflib/netsource/app-netsource-netapp_ontap.conf
- package/etc/test_parsers/app-vps-test-netapp_ontap.conf
- package/lite/etc/addons/netapp/app-netsource-netapp_ontap.conf
- tests/test_netapp.py
Add test for new netapp logtype.
> chore: add netapp test

- docs/sources/vendor/Citrix/netscaler.md
- package/enterprise/etc/conf.d/conflib/almost-syslog/app-almost-syslog-citrix_netscaler.conf
- package/etc/conf.d/conflib/almost-syslog/app-almost-syslog-citrix_netscaler.conf
- package/lite/etc/addons/citrix/app-almost-syslog-citrix_netscaler.conf
- tests/test_citrix_netscaler.py
Adds environment variable to citrix netscaler parser to fix parsing of date format: `dd/mm/yyyy` instead of `mm/dd/yyyy`.
> fix: update citrix netscaler date parser

- docs/upgrade.md
- package/sbin/entrypoint.sh
This PR:
- updates entrypoint script with new signal handlers
- removes redundant variables: `SPLUNK_HEC_URL`, `SPLUNK_HEC_TOKEN`, `SC4S_DEST_SPLUNK_HEC_TLS_VERIFY`
- adds comments for better readability of code
> feat: update entrypoint script
