package/etc/conf.d/conflib/vendor_juniper/junos.conf, package/etc/conf.d/conflib/vendor_juniper/legacy.conf, package/etc/conf.d/log_paths/p_rfc3164-juniper-idp.conf, package/etc/conf.d/log_paths/p_rfc3164-juniper-junos.conf, package/etc/conf.d/log_paths/p_rfc_5424_strict-juniper-junos.conf, package/etc/context-local/splunk_index.csv, tests/test_juniper_junos_rfc3164.py, tests/test_juniper_junos_rfc5124.py, tests/test_juniper_legacy.py, tests/test_juniper_sslvpn.py
https://github.com/splunk/splunk-connect-for-syslog/issues/79
=> Fix for Juniper filter/index.csv

docs/sources.md
Resolves https://jira.splunk.com/browse/RHINO-302
=> Doc: document the SC4S filter for Juniper

package/etc/conf.d/log_paths/p_rfc3164-cisco_asa.conf, package/etc/conf.d/log_paths/p_rfc3164-cisco_ios.conf, package/etc/conf.d/log_paths/p_rfc3164-cisco_nx-os.conf, package/etc/conf.d/log_paths/p_rfc3164-fortinet_fortios.conf, package/etc/conf.d/log_paths/p_rfc5424_noversion-cisco_asa.conf, package/etc/conf.d/log_paths/p_rfc_5424_noversion-symantec_proxy.conf, package/etc/conf.d/log_paths/p_rfc_5424_strict-juniper_junos.conf
=> Add port paths

.readthedocs.yml
=> Fix/rtd submodules (#94)

package/etc/conf.d/filters/juniper/junos.conf, package/etc/conf.d/log_paths/p_rfc3164-juniper_junos.conf.tmpl, package/etc/conf.d/log_paths/p_rfc_5424_strict-juniper_junos.conf.tmpl, package/etc/context-local/splunk_index.csv
Update Juniper filter to include the strings
"PFE_FW_" and
"DFWD_"
in the $MESSAGE macro as candidates for the "juniper:junos:firewall" sourcetype
=> Update Juniper filter

docs/gettingstarted/docker-systemd-general.md, docs/gettingstarted/podman-systemd-general.md
UDP port 514 was left out of the docker/podman startup string in the unit file for systemd
=> Fix docs to include UDP 514

docs/gettingstarted/docker-swarm-general.md, docs/gettingstarted/docker-swarm-rhel7.md, docs/gettingstarted/docker-systemd-general.md, docs/gettingstarted/podman-systemd-general.md
Since some steps were optional, I didn't do them :) So I ran into errors. Revising to make the parts mandatory.
=> removing optional parts

docs/gettingstarted/docker-swarm-general.md, docs/gettingstarted/docker-swarm-rhel7.md, docs/gettingstarted/docker-systemd-general.md, docs/gettingstarted/podman-systemd-general.md
Update unit/yml files to reflect new single mount point
=> Update yml/unit files in runtime docs for single mount point

docs/gettingstarted/docker-swarm-general.md, docs/gettingstarted/docker-swarm-rhel7.md, docs/gettingstarted/docker-systemd-general.md, docs/gettingstarted/podman-systemd-general.md
Fix port ranges
Fix comment for docker-compose.yml based runtime files
Add UDP ports to unique port unit/yml files
=> Fix unique port unit/yml files

docs/sources.md, package/etc/conf.d/conflib/_splunk/splunkfields.conf, package/etc/conf.d/filters/checkpoint/splunk.conf, package/etc/conf.d/log_paths/p_rfc3164-checkpoint_splunk.conf.tmpl, package/etc/context_templates/splunk_index.csv, splunk/etc/apps/SA-syslog-ng/default/indexes.conf, tests/test_checkpoint.py
Add support for log exporter "Splunk" format this does not support CEF or RFC5424 format
=> Fixes #129 Support Checkpoint Splunk Log exporter format

.gitmodules, package/etc/conf.d/local/context/compliance_meta_by_source.conf, package/etc/context_templates/compliance_meta_by_source.conf, package/etc/context_templates/vendor_product_by_source.conf, package/etc/syslog-ng.conf
See release notes https://github.com/syslog-ng/syslog-ng/releases
=> Upgrade embedded syslog-ng to version 3.24.1

package/sbin/entrypoint.sh
This fix prevents an error on upgrade when changes are made to example configs
=> Fix 1.1 upgrade error

docs/gettingstarted/byoe-rhel7.md, docs/gettingstarted/podman-systemd-general.md
* Update unit file dependencies (Wants/After) for Podman/CentOS runtime
* Correct gomplate version command
=> Unit file dependencies/gomplate version

docs/sources/PaloaltoNetworks/index.md, package/etc/conf.d/conflib/_common/syslog_format.conf, package/etc/conf.d/filters/paloalto/panos.conf, package/etc/conf.d/log_paths/p_rfc3164-paloalto_panos.conf.tmpl, package/etc/go_templates/source_network.t, tests/test_palo_alto.py
* Support paloalto in non compliant IETF mode
* Support feature flag for ms level time stamps
=> Improve palo alto support

package/etc/conf.d/log_paths/p_rfc3164-checkpoint_splunk.conf.tmpl, tests/test_checkpoint.py
When checkpoint devices are configured for syslog they also output os syslog.
=> Support "nix" events from the OS running on checkpoint appliances

package/etc/conf.d/log_paths/p_rfc3164-checkpoint_splunk.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-cisco_acs.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-cisco_asa.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-cisco_ios.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-cisco_ise.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-cisco_nxos.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-forcepoint_webprotect.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-fortinet_fortios.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-infoblox.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-juniper_idp.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-juniper_junos.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-juniper_netscreen.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-juniper_nsm.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-juniper_nsm_idp.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-microfocus_arcsight.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-paloalto_panos.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-proofpoint_pps.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-zscaler_nss.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3165-symantec_brightmail.conf.tmpl, package/etc/conf.d/log_paths/p_rfc5424-noversion_cisco_asa.conf.tmpl, package/etc/conf.d/log_paths/p_rfc5424-noversion_symantec_proxy.conf.tmpl, package/etc/conf.d/log_paths/p_rfc5424-strict_juniper_junos.conf.tmpl, package/etc/conf.d/log_paths/p_rfc5424_epoch-cisco_meraki.conf.tmpl, package/etc/conf.d/log_paths/p_za_nix_syslog.conf.tmpl, package/etc/conf.d/log_paths/p_zz_fallback.conf.tmpl
fix template override variable in log paths
=> fix template override variable

docs/sources/VMWare/index.md, package/etc/conf.d/conflib/_common/templates.conf, package/etc/conf.d/destinations/splunk_hec.conf.tmpl, package/etc/conf.d/filters/VMware/nsx.conf, package/etc/conf.d/filters/VMware/vsphere.conf, package/etc/conf.d/log_paths/p_multi-vmware_nsx.conf.tmpl, package/etc/conf.d/log_paths/p_zz_fallback.conf.tmpl, package/etc/context_templates/splunk_index.csv, tests/test_checkpoint.py, tests/test_linux_syslog.py, tests/test_vmware.py
=> Feature/support vmware vsphere, nsx, and esx

docs/sources/InfoBlox/index.md
=> Update Infoblox manual link

docs/configuration.md, docs/performance.md, docs/sources/index.md, package/Dockerfile
* Add metadata override instructions
* Add template documentation
* Update performance/sizing docs
=> Docs update

package/etc/conf.d/filters/checkpoint/splunk.conf, package/etc/conf.d/log_paths/p_rfc3164-checkpoint_splunk.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-cisco_acs.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-cisco_asa.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-cisco_ios.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-cisco_ise.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-cisco_nxos.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-forcepoint_webprotect.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-fortinet_fortios.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-infoblox.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-juniper_idp.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-juniper_junos.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-juniper_netscreen.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-juniper_nsm.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-juniper_nsm_idp.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-microfocus_arcsight.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-paloalto_panos.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-proofpoint_pps.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-ubiquiti_unifi.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-zscaler_nss.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3165-symantec_brightmail.conf.tmpl, package/etc/conf.d/log_paths/p_rfc5424-noversion_cisco_asa.conf.tmpl, package/etc/conf.d/log_paths/p_rfc5424-noversion_symantec_proxy.conf.tmpl, package/etc/conf.d/log_paths/p_rfc5424-strict_juniper_junos.conf.tmpl, package/etc/conf.d/log_paths/p_rfc5424_epoch-cisco_meraki.conf.tmpl, package/etc/conf.d/log_paths/p_vmware_vsphere.conf.tmpl, package/etc/conf.d/log_paths/p_za_nix_syslog.conf.tmpl, package/etc/conf.d/log_paths/p_zz_fallback.conf.tmpl, package/etc/go_templates/source_network.t
* Remove storage of RAWMSG to save memory/disk
* Update Ubiquiti and Checkpoint log paths to remove dependency on RAWMSG
* Remove ineffective "unset" directives from all log paths
* Fix Ubiqutit log path for regex parsing
* Simplify/remove extraneous processing in log paths
* Add `sc4s_vendor_product` to vmware log path
* Fix product comment at top of all log paths
* Destination env var gomplate logic fixed for fallback; subsequent PR will address all other log paths
=> Remove RAWMSG from all configs

docs/configuration.md
* Update docs to reflect minor change to t_JSON_5424 template
=> Update docs for t_JSON_5424 template

package/etc/conf.d/log_paths/internal.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-checkpoint_splunk.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-cisco_acs.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-cisco_asa.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-cisco_ios.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-cisco_ise.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-cisco_nxos.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-forcepoint_webprotect.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-fortinet_fortios.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-infoblox.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-juniper_idp.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-juniper_junos.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-juniper_netscreen.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-juniper_nsm.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-juniper_nsm_idp.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-microfocus_arcsight.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-paloalto_panos.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-proofpoint_pps.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-ubiquiti_unifi.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3164-zscaler_nss.conf.tmpl, package/etc/conf.d/log_paths/p_rfc3165-symantec_brightmail.conf.tmpl, package/etc/conf.d/log_paths/p_rfc5424-noversion_cisco_asa.conf.tmpl, package/etc/conf.d/log_paths/p_rfc5424-noversion_symantec_proxy.conf.tmpl, package/etc/conf.d/log_paths/p_rfc5424-strict_juniper_junos.conf.tmpl, package/etc/conf.d/log_paths/p_rfc5424_epoch-cisco_meraki.conf.tmpl, package/etc/conf.d/log_paths/p_vmware_vsphere.conf.tmpl, package/etc/conf.d/log_paths/p_za_nix_syslog.conf.tmpl, package/etc/conf.d/log_paths/p_zz_fallback.conf.tmpl, package/etc/conf.d/log_paths/startup.conf.tmpl
* Fix gomplate log path logic
* Fix bugs with env variables for destinations
=> Log path gomplate logic and minor bug fixes

package/etc/conf.d/log_paths/p_rfc3164-zscaler_nss.conf.tmpl
* Add missing timestamp parsing to zscaler log path
=> Add timestamp parsing to zscaler log path

package/etc/conf.d/destinations/splunk_hec.conf.tmpl, package/etc/conf.d/destinations/splunk_hec_internal.conf.tmpl, package/etc/conf.d/destinations/splunk_hec_metrics.conf.tmpl
* Fix URL grooming when list of HEC URLs is specified
=> Fix URL grooming for list of HEC URLs

package/Dockerfile
* Update interval to 30s
* Include start time set to 15s
* Remove python source command
=> Update HEALTHCHECK to 30s interval; remove python source

package/etc/conf.d/local/config/log_paths/example.conf.tmpl, package/etc/local_config/log_paths/example.conf.tmpl
* Update local example to reflect latest gomplate changes to log paths.
=> Update local example to reflect latest log path changes

docs/gettingstarted/index.md, mkdocs.yml
* Fix table navigation
* Remove "single node" nomenclature; all are "single node"
=> Fix documentation navigation

package/etc/conf.d/destinations/splunk_hec.conf.tmpl
* Update batch-timeout() value from 1 to 1000 to reflect ms units.  Intended value still 1 second.
=> Update batch_timeout to reflect ms units

docs/gettingstarted/byoe-rhel7.md, docs/gettingstarted/podman-systemd-general.md, docs/upgrade.md
* Update upgrade doc to include unit file changes
* Fix two errors in runtime docs
=> Minor docs updates/corrections

package/sbin/entrypoint.sh
* Update version code to reference proper file `/VERSION`
* Comment out python source -- to be addressed in a future release
=> Fix version string in `/entrypoint.sh`

docs/configuration.md, docs/developing/index.md, docs/gettingstarted/docker-swarm-general.md, docs/gettingstarted/docker-swarm-rhel7.md, docs/gettingstarted/docker-systemd-general.md, docs/gettingstarted/podman-systemd-general.md, docs/upgrade.md, mkdocs.yml
* Add description to configuration and runtime docs for properly accounting for container volume growth
* Revert change to VMware nav to properly match that of referenced directory/file.
* Change "Developing" to "Development"
* Update "Upgrade" for 1.1.0 changes
=> * Add detail on disk space needed for container volume

package/etc/conf.d/conflib/_common/templates.conf, package/etc/conf.d/filters/cisco/ios.conf, package/etc/conf.d/log_paths/lp-cisco_ios.conf.tmpl, package/etc/go_templates/source_network.t, pytest.ini, tests/test_cisco_ios.py
Enhance to address extra field before time stamp, uptime, and no host formats
=> Enhance cisco IOS

tests/test_ubiquiti_unifi.py
* Update Ubiquiti test to include search for host
=> Update Ubiquiti test to include search for host

package/etc/syslog-ng.conf
* Add Splunk copyright to syslog-ng.conf
=> Add Splunk copyright to syslog-ng.conf

package/etc/conf.d/log_paths/lp-sc4s_startup.conf.tmpl, tests/docker-compose.yml, tests/test_common.py
=> Correct sc4s:events:startup:out sourcetype

package/etc/conf.d/log_paths/lp-sc4s_internal.conf.tmpl
* Update metrics portion of internal log path to check the alternate destination env vars for alternate destinations
=> Update internal log path for alt dest

package/etc/conf.d/log_paths/lp-sc4s_internal.conf.tmpl, package/etc/conf.d/log_paths/lp-sc4s_startup.conf.tmpl
* Fix incorect default for `SC4S_DEBUG_STDOUT`
=> Fix incorrect default for `SC4S_DEBUG_STDOUT`

docs/configuration.md, docs/gettingstarted/docker-swarm-general.md, docs/gettingstarted/docker-swarm-rhel7.md, docs/gettingstarted/docker-systemd-general.md, docs/gettingstarted/index.md, docs/gettingstarted/podman-systemd-general.md, docs/troubleshooting.md, package/etc/go_templates/source_network.t
* Update troubleshooting docs
* Refine gettingstarted runtime docs
* Update default receive buffer to 16 MB (from 2 MB)
=> Update troubleshooting docs

package/etc/conf.d/local/config/log_paths/lp-example.conf.tmpl, package/etc/local_config/log_paths/lp-example.conf.tmpl
* Update `lp-example.conf.tmpl` to include env variable support for alternate destinations
=> Update example log path to inclucde alt destination

package/etc/conf.d/destinations/splunk_hec_debug.conf.tmpl
* Update `d_hec_debug` to use gomplate to pick up post-tempated URL string
=> Update `d_hec_debug` to use gomplate

docs/configuration.md, docs/gettingstarted/index.md
* Fix documentation markdown relative links
=> Fix doc relative markdown links

package/Dockerfile, package/etc/conf.d/conflib/_common/templates.conf, package/etc/conf.d/log_paths/lp-snmp_traps.conf.tmpl, package/sbin/entrypoint.sh, package/snmp/snmptrapd.conf
Experimental changes for SNMP trap support
=> Experimental Support SNMP Traps

docs/sources/Cisco/index.md, package/etc/conf.d/filters/cisco/asa.conf
Cisco FTD syslog is the same as cisco ASA
=> Support cisco FTD as Cisco ASA

package/sbin/entrypoint.sh
Allow developers to kill syslog-ng and not end the container
=> Support SIGHUP and SIGTERM traps

package/etc/conf.d/filters/f5/bigip.conf.tmpl
* Update f_f5_bigip_message filter to properly handle single-digit dates.
=> f5 message filter single digit date

package/etc/conf.d/conflib/_common/templates.conf, tests/docker-compose.yml
* Add missing PID to `t_program_msg` template
=> Add PID to `t_program_msg` template

docs/configuration.md, mkdocs.yml
* Update advice to be more general regarding worker thread env variable
* Fix pfsense source doc link
=> Update advice on worker threads

package/etc/conf.d/filters/f5/bigip.conf.tmpl, tests/test_f5_bigip.py
* Add RFC 5424 event support for f5 log path
=> Add support for structured (RFC 5424) f5

package/etc/conf.d/filters/common_event_format/cef.conf, package/etc/conf.d/filters/common_event_format/cef.conf.tmpl, package/etc/conf.d/log_paths/lp-common_event_format.conf.tmpl, package/etc/go_templates/source_network.t
Use a custom parser to better handle the various sources which have unique ways of sending non standard data
=> Improve CEF parsing

package/etc/conf.d/destinations/rawmsg_file.conf
* Add file destination to capture RAWMSG.  Useful for pre-production raw message capture
=> Add file destination for raw message collection

package/etc/conf.d/log_paths/lp-zscaler_lss.conf.tmpl
* Clean up extraneous parser/rewrites in `lp-zscaler_lss.conf.tmpl`
* Previous code is functionally OK; this is a cleanup only
=> zscaler lss log path cleanup

package/etc/conf.d/conflib/_common/templates.conf
* Add template to output only the structured data (SDATA) portion of the 5424 event
=> Add new template for 5424 SDATA only

package/etc/conf.d/destinations/rawmsg_file.conf
* Refine rawmsg destination to not fire if `RAWMSG` macro is not set or null
=> Refine rawmsg destination

package/etc/conf.d/log_paths/lp-mcafee_epo.conf.tmpl, package/etc/context_templates/splunk_index.csv.example
* Add mcafee entry to `splunk_index.csv`
* Clean up log path
=> Add context entry for mcafee

docs/sources/Symantec/index.md, package/etc/conf.d/filters/symantec/ep.conf, package/etc/conf.d/log_paths/lp-symantec_ep.conf.tmpl, package/etc/context_templates/splunk_index.csv.example, tests/test_symantec_ep.py
@rfaircloth-splunk , @mkarlstrand-splunk  Please mark this as a beta support
=> Symantec Endpoint Protection filters

docs/configuration.md, docs/gettingstarted/docker-systemd-general.md, docs/gettingstarted/podman-systemd-general.md, package/etc/conf.d/conflib/_splunk/splunkfields.conf.tmpl, package/etc/conf.d/destinations/splunk_hec.conf.tmpl
* Fix indexed field gomplate template
* Add "none" as an option for indexed fields
* Update and expand docs
=> Fix indexed field gomplate template

docs/gettingstarted/docker-systemd-general.md, docs/gettingstarted/podman-systemd-general.md, package/etc/conf.d/conflib/_splunk/splunkfields.conf.tmpl
* Update `splunkfields.conf.tmpl` gomplate logic to fix typo in desthost field
=> Update splunkfields gomplate template logic

docs/sources/Cisco/index.md, package/etc/conf.d/log_paths/lp-cisco_asa.conf.tmpl, tests/test_cisco_asa.py
=> Support cisco firepower unified logs

package/etc/go_templates/source_network.t
* Update `source_network.t` gomplate construct to properly parse tls multi-port
=> TLS multi-port template fix

docs/configuration.md
* Fix rendering of diskbuffer section in `configuration.md`
=> Fix rendering of diskbuffer section in `configuration.md`

package/etc/conf.d/conflib/_common/date-parser_nofilter.conf.tmpl, package/etc/conf.d/log_paths/lp-f5_bigip.conf.tmpl, package/etc/conf.d/log_paths/lp-fortinet.conf.tmpl, package/etc/conf.d/log_paths/lp-zscaler_lss.conf.tmpl
* Shorten rogue/dtparse `sc4s_error` indexed field
=> Shorten rogue/dtparse indexed field

docs/configuration.md
* Update `SC4S_ARCHIVE_<SOURCE>` variable name in docs to omit the incorrect "LISTEN" portion
* Refine disk buffer "NOTES" bullet list
=> Update `SC4S_ARCHIVE_<SOURCE>` variable

docs/upgrade.md
Minor doc update for the version upgrade process.
=> Docs: Upgrade process updated

package/sbin/entrypoint.sh
* Update spelling/grammar in status messages in `entrypoint.sh`
=> * Update spelling/grammar in `entrypoint.sh`

package/sbin/entrypoint.sh
* Update status message with newline to get around lack of one from prior curl command
* Correct spelling
=> Update status msg with newline

package/sbin/entrypoint.sh
* Refine HEC connectivty test at startup
=> `/entrypoint.sh` HEC connectivity test

package/etc/conf.d/filters/forcepoint/webprotect.conf
Vendor field has changed to Forcepoint in 8.x
=> Support new version of forcepoint webprotect

package/sbin/entrypoint.sh
Fixes #539 Address race condition where the old file is replaced before the read of new is finished
=> Address race condition in entrypoint.sh

docs/gettingstarted/docker-systemd-general.md, docs/gettingstarted/index.md, docs/gettingstarted/podman-systemd-general.md
Added missing indexes in Splunk indexes list and Removed configure SC4S Default Listening Ports section
=> Minor doc changes

package/etc/conf.d/log_paths/lp-paloalto_panos.conf.tmpl, tests/test_palo_alto.py
Fixes #554 handle commas inside double quoted fields
=> Fixes #554 handle commas inside double quoted fields

docs/sources/Cisco/index.md, package/etc/conf.d/filters/cisco/cisco_syslog.conf, semtag, tests/test_cisco_ios.py
Change Cisco IOS to allow for a colon on the syslog version position
=> [FILTERMOD]  Cisco FPMC chassis support

package/etc/conf.d/log_paths/lp-snmp_traps.conf.tmpl, package/sbin/entrypoint.sh
* Provide snmp collection switch
=> Provide snmp collection switch

docs/sources/Loggen/index.md, package/etc/conf.d/log_paths/lp-syslogng_loggen.conf.tmpl, tests/test_loggen.py
Added changes for BSD format in loggen logpath.
Added test for BSD format.
Added sample loggen commands in doc-notes.
=> Added BSD format support in loggen filter

package/etc/conf.d/filters/cisco/cisco_syslog.conf, tests/test_cisco_ios.py
Adjust airOS and Nexsus to address event with no HOST but with TZ indicator
=> [filterchange] Cisco Nexus

docs/troubleshooting.md
Troubleshooting guide format change to match https://docs.splunk.com/Documentation/Splunk/8.0.4/Troubleshooting/Cantfinddata
Added Timezone/ server out of space/kernel memory warnings.
=> Troubleshooting/problem >solution

docs/troubleshooting.md
Reverts splunk/splunk-connect-for-syslog#593
=> Revert "Troubleshooting/problem >solution"

docs/gettingstarted/docker-systemd-general.md, docs/gettingstarted/podman-systemd-general.md, docs/index.md
* Update unit files for proper restart behavior
* Update pathnames for `sleep` and `conntrack`
* Update SC4S docs home page to indicate fully supported status
=> Unit file updates/home page update

package/sbin/entrypoint.sh
* Update `entrypoint.sh` to honor value of `SC4S_DEST_SPLUNK_HEC_TLS_VERIFY` during HEC connectivity check
=> Update `entrypoint.sh` HEC check

package/etc/conf.d/log_paths/lp-cisco_acs.conf.tmpl
=> [fix] revert acs changes

package/etc/conf.d/log_paths/lp-common_event_format.conf.tmpl
* CEF:  Imperva WAF timestamp parsing fix
=> CEF:  Imperva WAF timestamp parsing

tests/test_cisco_wsa.py
=> Fixed Cisco WSA python test

docs/gettingstarted/index.md
* Add item to remove pull from unit file in local container guidance
* Clarify use of internal (syslog-ng based) load balancing vs. external LB
=> Update local container guidance

docs/gettingstarted/index.md
* `readthedocs` markdown workaround
=> `readthedocs` markdown workaround

.circleci/config.yml
It creates a bookmarked pdf for all the .md docs in the repo. Please review
=> Step added in ci pipeline for pdf generation

package/etc/conf.d/log_paths/lp-cisco_acs.conf.tmpl, package/etc/conf.d/log_paths/lp-cisco_ise.conf.tmpl, package/etc/conf.d/log_paths/lp-log_extended_event_format.conf.tmpl, tests/test_cisco_ise.py
Correct inclusion of last segment twice
=> [filtermod] Cisco ACS and ISE

docs/sources/Cisco/index.md, package/etc/conf.d/filters/cisco/ace.conf, package/etc/conf.d/log_paths/lp-cisco_ace.conf.tmpl, package/etc/context_templates/splunk_metadata.csv.example, tests/test_cisco_ace.py
=> [filteradd] Support Cisco ACE legacy products

package/etc/conf.d/conflib/_splunk/splunk_context.conf, package/etc/conf.d/log_paths/lp-common_event_format.conf.tmpl, package/etc/conf.d/log_paths/lp-log_extended_event_format.conf.tmpl, package/etc/context_templates/splunk_metadata.csv.example
* Add default "unknown" selector to p_add_context_splunk()
=> Add default selector to p_add_context_splunk()

.circleci/config.yml
This PR improves readability of the circleci config by utilizing the matrix syntax
=> [feature] Utilize CircleCI Matrix Syntax

package/etc/conf.d/local/config/filters/example.conf, package/etc/local_config/filters/example.conf, package/etc/local_config/log_paths/lp-example.conf.tmpl
* Update `local_config` filesystem to include new versions of example files
=> Update `local_config` filesystem

docs/sources/Schneider/index.md
* [docs] Update  `SC4S_LISTEN_SCHNEIDER_APC_TCP_PORT` and `SC4S_LISTEN_SCHNEIDER_APC_UDP_PORT` to correct missing `LISTEN` prefix
=> Update incorrect Schneider LISTEN variable

package/etc/conf.d/conflib/_common/f_null_queue.conf, package/etc/conf.d/log_paths/lp-aaa-null_queue.conf.tmpl
* Consolidate null queue filter into log path
* Remove separate filter file from common area
=> Consolidate null queue filter

docs/gettingstarted/byoe-rhel8.md
* Update version in BYOE runtime doc to v.1.33.0
=> Update version to v.1.33.0

docs/gettingstarted/byoe-rhel8.md
* Update `entrypoint.sh` file location for BYOE
=> Update `entrypoint.sh` file location for BYOE

docs/gettingstarted/index.md
* Fix broken BYOE link (new filename)
* Refine prerequisite for NLB
=> Docs update to fix broken BYOE link

package/sbin/entrypoint.sh
* Add proper exit code to SIGTERM handler
=> Add proper exit code to SIGTERM handler

docs/gettingstarted/byoe-rhel8.md, package/sbin/entrypoint.sh
* Fix hardcoded paths for goss in `entrypoint.sh`
=> Fix hardcoded paths for goss in `entrypoint.sh`

docs/sources/InfoBlox/index.md, package/etc/conf.d/log_paths/lp-infoblox.conf.tmpl, package/etc/context_templates/splunk_metadata.csv.example, package/etc/context_templates/vendor_product_by_source.conf.example, tests/test_infoblox.py
Jira: ADDON-29621, ADDON-28603, ADDON-28680
* Add support for the Infoblox events
=> Support infoblox

package/etc/conf.d/log_paths/lp-zzw-simple_port.conf.tmpl
* Add gomplate test to check for existence of SIMPLE env vars
=> Add gomplate test for variable existence

tests/conftest.py
* Increase pytest port range due to new `SIMPLE` ports
=> Increase pytest ports

package/etc/conf.d/log_paths/lp-paloalto_panos.conf.tmpl, tests/conftest.py, tests/test_palo_alto.py
* Add IETF (5424) support for Palo Alto Networks
=> Add IETF (5424) support for Palo Alto Networks

.circleci/config.yml, package/etc/conf.d/log_paths/lp-citrix-netscaler.conf.tmpl, package/etc/go_templates/sp_ns_citrix_netscaler.t, tests/conftest.py
Update Citrix template for compatibility with current TA
=> [filtermod] Correct Citrix Template

package/etc/conf.d/log_paths/lp-checkpoint_splunk.conf.tmpl, tests/test_checkpoint.py
Address issue where product value is null from source causing lost events and re-enable feature using SC4S_LISTEN_CHECKPOINT_SPLUNK_NOISE_CONTROL
=> [filtermod] Restore and improve checkpoint noise control

docs/sources/Pulse/index.md, mkdocs.yml, package/etc/conf.d/log_paths/lp-pulse_connect_secure.conf.tmpl, package/etc/context_templates/splunk_metadata.csv.example, package/etc/go_templates/source_network.t, package/etc/goss.yaml.tmpl, tests/conftest.py, tests/docker-compose.yml, tests/test_pulsesecure.py
Support Pulse Connect secure product using TCP (RFC5687) and UDP.
=> Support Pulse Secure Connect and resolve goss template for multiple ports

deploy/k8s-microk8s/sc4s-ds.yaml, deploy/k8s-microk8s/sc4s-infra.yaml
=> Fix k8s yaml defaults

package/etc/conf.d/conflib/_common/syslog_format.conf
Allow optional Z with TZ offset
=> [filtermod] Refine RFC5424 Date check

package/etc/conf.d/log_paths/lp-pulse_connect_secure.conf.tmpl
=> [fix] Pulse Connect Secure not opening 6587 without TCP/UDP

docs/gettingstarted/byoe-rhel8.md
* Update byoe runtime for more secure goss install
=> Update byoe runtime for more secure goss install

package/sbin/entrypoint.sh
* Use merged `splunk_metadata.csv` for HEC check
=> Use merged `splunk_metadata.csv` for HEC check

package/etc/conf.d/log_paths/lp-checkpoint_splunk.conf.tmpl
* [filtermod] fix CHPT filter for System Monitor
=> [filtermod] fix CHPT filter for System Monitor

docs/configuration.md
* [docs] change default for reverse DNS to `no`
=> [docs] change default for reverse DNS to `no`

package/etc/conf.d/log_paths/lp-checkpoint_splunk.conf.tmpl, tests/test_checkpoint.py
Remove duplicate use of kv parser and remove PRI from test cases not sent by real devices
=> [filtermod] checkpoint update test case

docs/sources/Cisco/index.md, package/etc/conf.d/log_paths/lp-cisco_z_ios.conf.tmpl
* [fix] docs incorrect for UCS
* [fix] alternate destination incorrect for CIMC
=> [fix] CIsco UCS/CIMC

package/sbin/entrypoint.sh
correct the following false error
=> [fix] entrypoint url test

docs/sources/McAfee/index.md
Reverts splunk/splunk-connect-for-syslog#816
=> Revert "update index configuration section for markdown formatting"

package/etc/conf.d/log_paths/lp-checkpoint_splunk.conf.tmpl
* Update CHPT log path filter to include additional events
* Include a default source in case Product is not set in event
=> [filter] Update CHPT filter for additional events

docs/sources/Cisco/index.md, package/etc/conf.d/log_paths/lp-cisco_hyperflex.conf.tmpl, package/etc/context_templates/splunk_metadata.csv.example, tests/test_cisco_hyperflex.py
=> [Filteradd] cisco hyperflex

docs/sources/Checkpoint/index.md, package/etc/conf.d/log_paths/lp-checkpoint_splunk.conf.tmpl
Make the checkpoint noise timer configurable and allow for aggregation using only the loguid as key
ref #ADDON-31240
=> feat(checkpoint): Make checkpoint noise timer configurable

docs/configuration.md, package/sbin/entrypoint.sh
* Remove extra mkdir for `local_config` directory
* Multiple typos in `configuration.md`
=> fix: entrypoint.sh

docs/configuration.md, package/sbin/entrypoint.sh
Reverts splunk/splunk-connect-for-syslog#868
=> Revert "fix: entrypoint.sh"

package/etc/conf.d/log_paths/lp-juniper_junos.conf.tmpl, tests/test_juniper_junos_rfc3164.py
https://jira.splunk.com/browse/ADDON-31368: Adding support for new juniper events from customer samples
=> ADDON-31368: Adding support for updown logs events

package/sbin/entrypoint.sh
* Remove pushd/popd due to stdout clutter
=> chore: Cleanup startup logs

deploy/k8s-microk8s/sc4s-ds.yaml
Update `sc4s_ds.yaml` to account for new container filesystem layout
=> fix:  Update k8s manifest mount points to match container fs structure

package/etc/go_templates/source_network.t
Reverts splunk/splunk-connect-for-syslog#907
=> Revert "Log path enhancements"

docs/sources/Pfsense/index.md
* Fix pfsense `LISTEN` environment variables
=> doc: correct pfsense unique port listen variables

package/etc/conf.d/log_paths/1/lp-cisco_fwsm.conf.tmpl
=> fix(cisco_fwsm): Template error due to search and replace of ace string

package/etc/patterndb-raw.d/f5.xml
Causes syslog to go to fallback
=> fix(f5): First of Month date issue

package/etc/patterndb.d/paloalto/logforwarder.xml
When processing these logs append the 1, allowing the existing ta to function.
=> fix(pan_cortex): Cortex logs are missing the first reserved field

package/etc/patterndb.d/imperva/securesphere.xml
In some cases Imperva sends a malformed header support this condition
=> fix(imperva_securesphere): Support broken CEF header

package/etc/conf.d/conflib/_common/t_templates.conf, package/etc/go_templates/source_network.t, package/etc/patterndb-raw.d/avi.xml, package/etc/patterndb-raw.d/cisco/ios.xml, package/etc/patterndb-raw.d/citrix/ns.xml, package/etc/patterndb-raw.d/f5.xml, package/etc/patterndb-raw.d/fe/cms.xml, package/etc/patterndb-raw.d/juniper/netscreen.xml, package/etc/patterndb-raw.d/radware/defesnepro.xml, package/etc/patterndb-raw.d/syslog.xml, package/etc/patterndb-raw.d/vectra_ai.xml, package/etc/patterndb.d/syslog-ng.xml, package/etc/syslog-ng.conf.tmpl
=> fix(source): Protect calls to RFC3164 parser from sources with PRI

tests/test_cyberark.py
CyberArl: Removed tokenize value from the event samples
=> CyberArk: Removed tokenize value from the event samples

docs/sources/HPe/index.md, package/etc/conf.d/conflib/raw/app-hpe_jetdirect.conf.tmpl, package/etc/conf.d/log_paths/1/lp-hpe_jetdirect.conf.tmpl, tests/test_hpe_jetdirect.py
=> feat(hpe_webjet): Support HP Printers and Scanners using WebJet

package/sbin/entrypoint.sh
When syslog-ng segfauls if a core is produced move to persistent storage, and restart syslog-ng with a new process without a new container.
=> fix(entrypoint): Improve handling of segmentation fault

docs/sources/HPe/index.md, package/etc/conf.d/conflib/net_source/app-aruba_clearpass.conf, package/etc/conf.d/conflib/raw/app-avi_controller_rfc5424.conf, package/etc/conf.d/conflib/raw/app-syslog_ms_comma.conf, package/etc/conf.d/sources/s-aruba_clearpass.conf.tmpl, package/etc/context_templates/vendor_product_by_source.conf.example, package/etc/context_templates/vendor_product_by_source.csv.example, tests/test_aruba_clearpass.py
feat(source): Support malformed bsd syslog with YYYY-MM-DD HH:MM:SSS,fff format.
fix(avi): More specific filter preventing over collection of non avi events
=> feat(aruba_clearpass): Support Aruba clearpass

docs/configuration.md, docs/gettingstarted/index.md
Correct UDP receive buffer size (17039360)
=> docs: correct buffer size

docs/configuration.md
Clarify SSL option list format
=> doc: Clarify ssl-options

docs/gettingstarted/quickstart_guide.md
doc:
* Correct quickstart formatting errors
* Correct buffer size (add missing zero)
=> doc: quickstart

package/sbin/entrypoint.sh
Reduce false errors for unused index only check events and fallback index
=> fix(entrypoint): Check only fallback and events index on startup

.circleci/config.yml, package/etc/conf.d/conflib/cef/app-cef-trendmicro_deep_agent.conf, package/etc/conf.d/conflib/cef/app-cef-vectra.conf, package/etc/conf.d/conflib/net_source/app-pfsense.conf, package/etc/context_templates/splunk_metadata.csv.example, package/sbin/entrypoint.sh, tests/docker-compose.yml, tests/test_common.py
Create the examples but do not copy examples to active touch local config files to prevent errors for missing files only
=> fix(entrypoint): Don't create full defaults

package/etc/conf.d/conflib/net_source/app-null_queue.conf
Resolve issue where  null queue was ignored
=> fix(null_queue): Null queue from vendor_product_by_source_ignored

package/etc/conf.d/conflib/raw/app-checkpoint_splunk.conf.tmpl
This hidden feature flag enables the reduction of noise by null_queue "accepted" fw/url events where the bytes field is empty.
=> feat(checkpoint_splunk): Experimental fw noise

package/etc/conf.d/conflib/syslog/app-f5_bigip.conf, tests/test_f5_bigip.py
Some of the sourcetypes for F5 BigIP were not getting assigned properly. Modified the filter so that the sourcetypes will be correctly assigned.
=> fix(f5_bigip): Additional fixes for f5:bigip:syslog

package/etc/conf.d/conflib/_common/r_dest.conf, package/etc/conf.d/conflib/net_source/app-spectracom-ntp.conf, package/etc/conf.d/destinations/archive_file.conf, package/etc/conf.d/sc4slib/source_snmp/plugin.py, package/etc/conf.d/sc4slib/source_syslog/plugin.jinja, package/etc/conf.d/sources/internal.conf
This reverts commit 278cdffb055e5b1edda6277c4a6a94f170990c79.
=> Revert "fix(archive): Single dest_key archive not working"

package/etc/conf.d/conflib/_common/t_splunk_hec_metric_event.conf, package/etc/conf.d/conflib/_common/t_splunk_hec_metric_multi.conf, package/etc/conf.d/conflib/_common/t_splunk_hec_metric_single.conf, package/etc/conf.d/conflib/_splunk/splunkfields.conf, package/etc/conf.d/sources/internal.conf
meta fields were missing the first "s" due to incorrect use of strip
=> fix(metrics): Incorrect host and missing meta

package/sbin/entrypoint.sh
=> fix(entrypoint): Correct fallback check based on splunk_metadata.csv

.github/workflows/coc.yaml, docs/sources/Microfocus/index.md
=> doc(microfocus): Update doc links for microfocus

docs/sources/Alsid/index.md, mkdocs.yml, package/etc/conf.d/conflib/_common/t_templates.conf, package/etc/conf.d/conflib/syslog/app-alsid_syslog.conf, tests/test_alsid.py
=> feat(alsid): Add support for Alsid

docs/sources/Tenable/index.md, mkdocs.yml, package/etc/conf.d/conflib/syslog/app-tenable_syslog.conf, tests/test_tenable.py
Adding the sc4s support for the Tenable.nnm logs
=> ADDON-37084: Adding the support for Tenable.nnm logs

package/etc/conf.d/conflib/syslog/app-zscaler_lss.conf
=> fix(zscaler_lss): Incorrectly setting SOURCE metadata

docs/sources/Checkpoint/index.md, package/etc/conf.d/conflib/raw/app-checkpoint_splunk.conf, package/etc/conf.d/conflib/syslog/app-checkpoint_syslog.conf
=> fix: Correct ordering of host selection

package/etc/conf.d/conflib/_splunk/splunkfields.conf
Indexed fields for severity and facility should be set after parsing
=> fix: Correct reporting of severity and facility

docs/sources/Thycotic/index.md, mkdocs.yml, package/etc/conf.d/conflib/cef/app-cef-thycotic_secret_server.conf
=> feat(thycotic): support secret server

docs/sources/Polycom/index.md, mkdocs.yml, package/etc/conf.d/conflib/syslog/app-polycom_rprm.conf, tests/test_polycom.py
=> feat(polycom): Support RPRM

.circleci/config.yml, package/etc/conf.d/conflib/syslog/app-splunk_cooked.conf, tests/test_splunk.py
Experimental config paired with a Splunk side configuration to allow sc4s to accept data parsed by a Splunk HWF https://gist.github.com/rfaircloth-splunk/fe0f051fbedfefd13c5f56dfeb0a8b3b
=> feat: EXPERIMENTAL Support HWF source

docs/configuration.md
patterns were incorrectly switched
swapping to correct documentation
=> [DOC] Correct ARCHIVE_MODE patterns

package/Dockerfile
This reverts commit 0a1fda56cd062db0e6ad4b3f693e854459e066d6.
=> Revert "chore: pin docker image (#1215)"

Pipfile, docs/sources/NetApp/index.md, mkdocs.yml, package/etc/conf.d/conflib/syslog/app-netapp_ontap.conf, tests/test_netapp.py
=> feat(netapp): Support Netapp Ontap EMS

.github/workflows/agreements.yaml
Similar to https://github.com/splunk/addonfactory-ucc-generator/blob/137d9734649111068e13a2eafbb0a164d287af8a/.github/workflows/agreements.yaml
=> ci: allowlist dependabot[bot] for CLA and COC

package/etc/conf.d/sc4slib/dest_hec/plugin.jinja
When disabling diskbuffer TLS was also disabled on dest hec
=> fix: Unable to disable disk buffer

README.md, docs/sources/Cisco/index.md
=> doc: Updated licensing hyperlinks

.github/workflows/ci-main.yaml
workaround for issue described here https://github.com/splunk/addonfactory-repository-template/pull/183
=> ci: use nodejs 14

docs/sources/GitHub/index.md, package/etc/conf.d/conflib/syslog/app-github_ent.conf, tests/test_github_ent.py
JIRA ID : https://jira.splunk.com/browse/ADDON-44226
=> feat(GitHub): ADDON-44226 Support for GitHub Enterprise

docs/sources/Cylance/index.md, mkdocs.yml, package/etc/conf.d/conflib/syslog/app-cylance_protect.conf, tests/test_cylance_protect.py
=> feat: support cylance

docs/sources/Microfocus/index.md, docs/upgrade.md, package/sbin/entrypoint.sh
"MICROFOCUS_ARCSIGHT" vendor_product vars were replaced with "CEF" please see doc on upgrade
=> feat!: Remove legacy MICROFOCUS_ARCSIGHT vars

package/etc/conf.d/sc4slib/global_options/plugin.jinja, package/etc/conf.d/sc4slib/global_options/plugin.py, package/etc/syslog-ng.conf
=> feat: Dynamic global options

package/etc/conf.d/conflib/almost-syslog/app-syslog-aaa-citrix_netscaler.conf, package/etc/conf.d/conflib/almost-syslog/app-syslog-aaa-citrix_netscaler_svm.conf, package/etc/conf.d/conflib/almost-syslog/app-syslog-aaa-juniper_netscreen_raw.conf, package/etc/conf.d/conflib/almost-syslog/app-syslog-aaa-zscaler-nss-alerts.conf, package/etc/conf.d/conflib/almost-syslog/app-syslog-ccc-badversion.conf, package/etc/conf.d/conflib/almost-syslog/app-syslog-ccc-bsd-isotime.conf, package/etc/conf.d/conflib/almost-syslog/app-syslog-ccc-wlevelword.conf, package/etc/conf.d/conflib/almost-syslog/app-syslog-cisco_syslog.conf, package/etc/conf.d/conflib/almost-syslog/app-syslog-epoch.conf, package/etc/conf.d/conflib/almost-syslog/app-syslog-hip.conf, package/etc/conf.d/conflib/almost-syslog/app-syslog-isodate.conf, package/etc/conf.d/conflib/almost-syslog/app-syslog-json.conf, package/etc/conf.d/conflib/raw/app-checkpoint_splunk.conf, package/etc/conf.d/conflib/raw/app-raw-isodate.conf, package/etc/conf.d/conflib/syslog/app-avi_controller_rfc5424.conf, package/etc/conf.d/conflib/syslog/app-checkpoint_syslog.conf, package/etc/conf.d/conflib/syslog/app-fireeye-json.conf, package/etc/conf.d/sc4slib/source_syslog/plugin.jinja
Cleanup use of store raw message and memory impact
=> fix: Cleanup use of store-raw-message

docs/sources/Arista/index.md, mkdocs.yml, package/etc/conf.d/conflib/almost-syslog/app-almost-syslog-arista_eos.conf, tests/test_arista.py
=> feat: Support Arista Switches

docs/sources/Cohesity/index.md, mkdocs.yml, package/etc/conf.d/conflib/syslog/app-syslog-cohesity_cluster_audit.conf, package/etc/conf.d/conflib/syslog/app-syslog-cohesity_cluster_dataprotection.conf, tests/test_cohesity.py
=> feat: Support Cohesity

package/etc/conf.d/conflib/syslog/app-syslog-hpe_procurve_fmt1.conf, tests/test_hpe_procurve.py
Support the literal '(Stack)' prior to the program field
=> fix: HPE Procurve "stacked"

docs/sources/PaloaltoNetworks/index.md, package/etc/conf.d/conflib/cef/app-cef-pan-xsoar.conf
=> feat: Support Palo Alto Networks Cortex XSOAR

docs/sources/Solace/index.md, mkdocs.yml, package/etc/conf.d/conflib/syslog/app-syslog-solace_eventbroker.conf, tests/test_solace.py
=> feat: support solace event broker

docs/sources/Alsid/index.md, docs/sources/Tenable/index.md, package/etc/conf.d/conflib/syslog/app-syslog-tenable_ad.conf, package/etc/conf.d/sources/source_syslog/plugin.jinja, tests/test_tenable.py
=> feat: support tenable ad

package/etc/conf.d/conflib/app-fix-invalid-program/app-fix-invalid-program-dashdash.conf, package/etc/conf.d/conflib/app-fix-invalid-program/app-fix-invalid-program-epoch.conf, package/etc/conf.d/conflib/app-fix-invalid-program/app-fix-invalid-program-ipv4.conf, package/etc/conf.d/conflib/app-fix-invalid-program/app-fix-invalid-program-ne.conf, package/etc/conf.d/conflib/app-fix-invalid-program/app-fix-invalid-program-z_bsdconvention.conf, package/etc/conf.d/conflib/netsource/app-netsource-cisco_wsa.conf, package/etc/conf.d/conflib/netsource/app-netsource-cisco_wsa_11_7.conf, package/etc/conf.d/conflib/netsource/app-netsource-cisco_wsa_splunk.conf, package/etc/conf.d/conflib/syslog/app-syslog-fireeye-json.conf, package/etc/conf.d/conflib/syslog/app-syslog-pure_storage.conf, package/etc/conf.d/sources/source_syslog/plugin.jinja
The PR for bomgar allows a "." in the program value however wsa is placing an epoch timestamp with ms in the program field breaking the wsa format.
=> fix: issue with wsa in beta

package/etc/conf.d/conflib/syslog/app-syslog-juniper.conf, package/etc/conf.d/conflib/syslog/app-syslog-juniper_junos_structured.conf, package/etc/conf.d/conflib/syslog/app-syslog-juniper_junos_unstructured.conf
This PR splits the structured and unstructured parsers for ease of maint.
=> fix: improve junos parsers

docs/sources/vendor/Cisco/cisco_cmc.md, package/etc/conf.d/conflib/almost-syslog/app-almost-syslog-cisco_cmc.conf, package/etc/conf.d/conflib/netsource/app-netsource-cisco_cmc.conf, package/etc/test_parsers/app-vps-test-cisco_cmc.conf, tests/test_cisco_cmc.py
=> feat: Support Cisco CMC

docs/sources/vendor/NetScout/arbor_edge.md, package/etc/conf.d/conflib/cef/app-cef-netscout_arbor-edge.conf, tests/test_netscout_arbor-edge.py
fixes #1433 Supporting recommended CEF mode only
=> feat: Support netscout arbor edge

docs/sources/vendor/Dell/sonicwall.md, package/etc/conf.d/conflib/syslog/app-syslog-dell_sonicwall-firewall.conf, tests/test_dell_sonicwall.py
=> feat: Support Dell Soniicwall

package/etc/conf.d/conflib/fallback/app-fallback-json.conf, package/etc/conf.d/conflib/netsource/app-netsource-vmware_esx_json.conf, package/etc/conf.d/conflib/syslog/app-syslog-vmware_esx.conf, package/etc/conf.d/conflib/syslog/app-syslog-vmware_nsx.conf, package/etc/conf.d/conflib/syslog/app-syslog-vmware_vcenter.conf, package/etc/conf.d/conflib/syslog/app-syslog-vmware_view.conf, package/etc/test_parsers/app-vps-test-vmware_vcenter.conf
Additional vmware specific filters and vsan json
=> feat(vmware): imporv vmware add vsan sources

docs/sources/vendor/Aruba/ap.md, docs/sources/vendor/Aruba/clearpass.md, docs/sources/vendor/Brocade/switch.md, docs/sources/vendor/Buffalo/index.md, docs/sources/vendor/Checkpoint/firewallos.md, docs/sources/vendor/Cisco/cisco_esa.md, docs/sources/vendor/Cisco/cisco_meraki.md, docs/sources/vendor/Cisco/cisco_ms.md, docs/sources/vendor/Cisco/cisco_wsa.md, docs/sources/vendor/Dell/cmc.md, docs/sources/vendor/Dell/rsa_secureid.md, docs/sources/vendor/F5/bigip.md, docs/sources/vendor/IBM/datapower.md, docs/sources/vendor/InfoBlox/index.md, docs/sources/vendor/Mikrotik/routeros.md, docs/sources/vendor/Pfsense/firewall.md, docs/sources/vendor/Proofpoint/index.md, docs/sources/vendor/Raritan/dsx.md, docs/sources/vendor/Schneider/apc.md, docs/sources/vendor/Sophos/webappliance.md, docs/sources/vendor/Spectracom/index.md, docs/sources/vendor/Ubiquiti/unifi.md, docs/sources/vendor/VMWare/index.md, docs/sources/vendor/VMWare/vsphere.md, docs/sources/vendor/Wallix/bastion.md
=> doc: correct local path for parsers

package/etc/conf.d/conflib/almost-syslog/app-almost-syslog-citrix_netscaler.conf, package/etc/conf.d/conflib/syslog/app-syslog-citrix-netscaler_aaa.conf, package/etc/conf.d/conflib/syslog/app-syslog-citrix_netscaler_svm.conf
=> fix: citrix msg format issue

package/etc/conf.d/conflib/syslog/app-syslog-zscaler_nss_proxy.conf
=> fix(scaler): dns sourcetype wrong

package/etc/conf.d/conflib/cef/app-cef-trendmicro_deep_agent.conf
=> fix: trend class values

docs/sources/vendor/Cisco/cisco_ms.md
=> doc: cisco ms

package/etc/conf.d/conflib/almost-syslog/app-almost-syslog-cisco_syslog.conf, package/etc/conf.d/conflib/syslog/app-syslog-arista_eos.conf, package/etc/conf.d/conflib/syslog/app-syslog-cisco_syslog.conf
Events identified as config agent
=> fix: Arista Issue with some ConfigAgent

package/Dockerfile, package/etc/conf.d/conflib/_splunk/fix_dns.conf, package/etc/conf.d/conflib/syslog/app-syslog-leef.conf, package/etc/pylib/parser_fix_dns.py, package/etc/pylib/parser_leef.py, package/sbin/entrypoint.sh, poetry.lock, pyproject.toml
Improvement for dev experience move python to .py files outside of .conf
=> chore: move python code from conf to files

docs/sources/vendor/Kaspersky/es.md, package/etc/conf.d/conflib/syslog/app-syslog-kaspersky_syslog.conf, tests/test_kaspersky.py
=> feat: support kaspersky 5424

.gitignore, docs/sources/vendor/Fortinet/fortimail.md, package/etc/conf.d/conflib/syslog/app-syslog-fortigate_fortios.conf, package/etc/conf.d/conflib/syslog/app-syslog-fortigate_fortiweb.conf, tests/test_fortinet_web.py
Fortiweb "vendor" field will be corrected to fortinet
New support for fortimail
fixes #1518
=> feat: Support fortimail and correct fortiweb vendor

docs/sources/vendor/StealthWatch/StealthIntercept.md, package/etc/conf.d/conflib/syslog/app-syslog-stealthbits_stealthintercept.conf, package/etc/conf.d/conflib/syslog/app-syslog-stealthbits_stealthintercept_alerts.conf, package/etc/pylib/parser_stealthbits.py, tests/test_stealthbits.py
=> feat: support stealthbit StealthIntercept

package/etc/conf.d/conflib/cisco-syslog/app-cisco-cisco_viptela.conf, tests/test_cisco_viptela.py
Update app-cisco-cisco_viptela.conf
=> fix: update viptela based on better samples

package/etc/conf.d/conflib/syslog/app-syslog-fortigate_fortios.conf, package/etc/conf.d/conflib/syslog/app-syslog-fortigate_fortiweb.conf
Forti is now using ms in the epoch field
=> fix: fortigate ts

docs/sources/vendor/Checkpoint/logexporter_5424.md, package/etc/conf.d/conflib/raw/app-raw-checkpoint_splunk.conf, package/etc/conf.d/conflib/syslog/app-syslog-checkpoint_syslog.conf, tests/test_checkpoint_syslog_rfc5424.py
JIRA: https://splunk.atlassian.net/browse/ADDON-40282
Added CLI, Identity Awareness, and Endpoint Blades support
Corrected valid RFC5424 configuration steps in Checkpoint doc
=> feat(checkpoint): Adding support for Checkpoint R81.10

docs/sources/vendor/Fortinet/fortimail.md, package/etc/conf.d/conflib/syslog/app-syslog-fortigate_fortiweb.conf, tests/test_fortinet_web.py
fixes #1574
incorrect source type missed existing TA in splunk base
=> fix: fortimail wrong sourcetype

package/etc/conf.d/conflib/almost-syslog/app-almost-syslog-cisco_syslog.conf
=> fix: arista additional cases

package/etc/conf.d/sources/source_syslog/plugin.jinja, package/etc/conf.d/sources/source_syslog/plugin.py
If the user has not defined the initial buffer size return to using os default if the getting started guide docs are followed the default will be correct.
=> fix: buffer message

docs/sources/vendor/Dell/sonicwall.md, package/etc/conf.d/conflib/syslog/app-syslog-dell_sonicwall-firewall.conf, tests/test_dell_sonicwall.py
=> fix: Correct dell sonicwall fw

docs/sources/vendor/Riverbed/index.md, docs/sources/vendor/Riverbed/steelconnect.md, docs/sources/vendor/Riverbed/steelhead.md, package/etc/conf.d/conflib/netsource/app-netsource-riverbed_syslog.conf, package/etc/conf.d/conflib/syslog/app-syslog-riverbed_syslog.conf, tests/test_riverbed.py
This is a draft waiting for info on which riverbed product this is
=> feat: Support riverbed

package/etc/pylib/parser_cef.py, package/etc/pylib/parser_leef.py
CEF events with a "label" field but without the value field caused a drop
=> fix: cef dropping

docs/gettingstarted/docker-compose-MacOS.md
Please review. Mac does not support -v
=> docker-compose-MacOS.md

package/etc/conf.d/conflib/syslog/app-syslog-vmware_horizon.conf
=> fix: vmware horizon product key

docs/sources/vendor/Broadcom/dlp.md, package/etc/conf.d/conflib/netsource/app-netsource-symantec_dlp.conf, package/etc/conf.d/conflib/syslog/app-syslog-symantec_dlp.conf, tests/test_symantec_dlp.py
New docs were located allowing for a msg format based parser option in addition to the existing vps option.
=> feat: Improve Symantec (broadcom) DLP

package/etc/conf.d/conflib/syslog/app-syslog-barracuda_syslog.conf
Support WAF as a service where host name is "barracuda"
=> feat: support barracuda waf as a service

docs/sources/vendor/Cisco/cisco_dna.md, package/etc/conf.d/conflib/syslog/app-syslog-cisco_dna_syslog.conf, tests/test_cisco_dna.py
=> Filter/cisco dna #1629

docs/sources/vendor/Zscaler/nss.md, package/etc/conf.d/conflib/syslog/app-syslog-zscaler_nss_proxy.conf, tests/test_zscaler_tunnel.py
=> feat: zsclaer tunnel type added

docs/sources/vendor/Nutanix/cvm.md, package/etc/conf.d/conflib/syslog/app-syslog-nutanix.conf, tests/test_nutanix.py
=> feat: adding new filter for nutanix cvm

docs/sources/vendor/Broadcom/dlp.md, package/sbin/entrypoint.sh
=> fix: podman log and index for broadcom dlp

package/etc/conf.d/conflib/almost-syslog/app-almost-syslog-cisco_syslog.conf
=> fix: cisco timesync bug

docs/sources/vendor/Forcepoint/webprotect.md, package/etc/conf.d/conflib/syslog/app-syslog-forcepoint_webprotect.conf
=> fix: webprotect forcepoint key 

package/etc/syslog-ng.conf
=> fix: alternate dest advanced log path 0 added to conf

docs/sources/index.md
=> docs: fix example queue

package/etc/conf.d/destinations/dest_hec/plugin.jinja
=> feat: directory buffer byoe

package/etc/conf.d/destinations/archive_file.conf
Archive mode was not working for diode logs, this will fix this issue.
=> fix: archive mode fix

package/etc/conf.d/conflib/post-filter/app-postfilter-vmware_vsphere_cmmdsTimeMachineDump.conf, package/etc/conf.d/conflib/post-filter/app-postfilter-vmware_vsphere_invalidmultiline.conf, package/etc/conf.d/conflib/post-filter/app-postfilter-vmware_vsphere_localcli.conf, package/etc/conf.d/conflib/post-filter/app-postfilter-vmware_vsphere_sdrsInjector.conf, package/etc/conf.d/conflib/post-filter/app-postfilter-vmware_vsphere_storageRM.conf
=> fix: postfilter vmware vendor

docs/faq.md, package/etc/conf.d/log_paths/2/lp_dest_alts_global/plugin.jinja, package/etc/conf.d/plugin/app_parser_topics.conf
=> feat: new sc4s-finalfilter for resolving OOB postfilter conflict issue

package/etc/conf.d/conflib/syslog/app-syslog-netapp_ontap.conf, tests/test_netapp.py
Fix regex for netapp ontap- include hex characters in first field after host.
=> fix: fix regex for nodea netapp ontap

package/etc/conf.d/conflib/syslog/app-syslog-vmware_vsphere.conf
=> feat: add new programs handled by vmware_vsphere_esx

docs/faq.md, docs/resources/indexes.conf
**Update:**
- Required indexes file for SC4S added as a resource in repo.
- FAQ page updated with this guide.
=> All SC4S indexes files created on repo for ref.

package/etc/conf.d/conflib/almost-syslog/app-almost-syslog-airwatch.conf, tests/test_airwatch_rfc3164.py
* fix: airwatch logging
* fix: airwatch logging regex
=> fix: airwatch logging (#1919)

.github/workflows/ci-main.yaml, docs/gettingstarted/ansible-docker-podman.md, docs/gettingstarted/ansible-docker-swarm.md, docs/gettingstarted/ansible-mk8s.md, docs/gettingstarted/docker-compose-MacOS.md, docs/gettingstarted/docker-compose.md, docs/gettingstarted/docker-systemd-general.md, docs/gettingstarted/podman-systemd-general.md
- Location of example files for all ansible runtime environments modified.
- Location of **env_file** modified for all runtimes.
=> fix: Runtime Documentation files

docs/sources/vendor/NetApp/storage-grid.md, package/etc/conf.d/conflib/syslog/app-syslog-netapp_grid.conf, tests/test_netapp_grid.py
**Notes:**
- This parser is community requested parser.
- Support is limited to sourcetype.
=> feat: NetApp StorageGRID parser

.github/workflows/cd-baremtal.yaml, package/etc/conf.d/conflib/cef/app-cef-cisco_esa.conf, tests/test_cisco_esa.py
- Fix for Cisco ESA filter added.
- Checksum calculation for baremetal file added when released.
=> Fix cisco esa regex & checksum included

docs/destinations.md
=> docs: update the example for select

package/etc/conf.d/conflib/syslog/app-syslog-hpe_ilo.conf
=> feat: hp ilo new log type identification

docs/troubleshooting/troubleshoot_SC4S_server.md, package/etc/conf.d/conflib/syslog/app-syslog-cef.conf
=> feat: sc4s will not drop invalid CEF

docs/resources/parser_development/app-syslog-vmware_cb-protect_example.conf, docs/sources/vendor/Cisco/cisco_ios.md, docs/troubleshooting/troubleshoot_SC4S_server.md, package/etc/conf.d/conflib/almost-syslog/app-almost-syslog-cisco_syslog.conf, package/etc/conf.d/conflib/almost-syslog/app-almost-syslog-vmware_vsphere_bad5424.conf, package/etc/conf.d/conflib/raw/app-raw-bsd_nopri.conf, package/etc/conf.d/conflib/raw/app-raw-xml.conf, package/etc/conf.d/conflib/syslog/app-syslog-hpe_jetdirect.conf, package/etc/conf.d/conflib/syslog/app-syslog-vmware_cb-protect.conf
- Disable flags added for all dropping events
- Cisco IOS: flag added for allowing entire raw message without drop.
=> fix: Disable flags added for all dropping events

pyproject.toml
=> feat!: update syslog-ng version to 4.2 and base image to alpine

License.md, docs/sources/index.md, docs/sources/vendor/Cisco/cisco_asa.md
Added license file and fixed broken links.
=> docs: Add License file and fix broken links

package/etc/conf.d/conflib/syslog/app-syslog-sophos_firewall_xg.conf
I have read the Code of Conduct and I hereby accept the Terms
=> [FIX] Corrected Sophos XG filter

package/etc/conf.d/conflib/post-filter/app-postfilter-cisco_acs.conf, package/etc/conf.d/conflib/post-filter/app-postfilter-cisco_ise.conf, package/etc/conf.d/conflib/post-filter/app-postfilter-vmware_vsphere_invalidmultiline.conf, package/etc/conf.d/conflib/post-filter/app-postfilter-vmware_vsphere_sdrsInjector.conf, package/etc/conf.d/conflib/post-filter/app-postfilter-vmware_vsphere_storageRM.conf, package/etc/conf.d/log_paths/2/lp_dest_alts_global/plugin.jinja
Changing the state of parsers of log path as stateful.
=> fix: stateful state for parser

package/etc/conf.d/conflib/syslog/app-syslog-juniper_junos_unstructured.conf
New message discovered from juniper os device.
=> juniper_junos_unstructured: add message filter to junos

docs/sources/vendor/Thales/thales_vormetric.md, package/etc/conf.d/conflib/syslog/app-syslog-vormetric.conf, package/lite/etc/addons/thales/addon_metadata.yaml, package/lite/etc/addons/thales/app-syslog-vormetric.conf, package/lite/etc/config.yaml, tests/test_vormetric.py
Solves https://github.com/splunk/splunk-connect-for-syslog/issues/2289
=> feat: adding support for Thales Vormetric

docs/sources/vendor/Fortinet/fortimail.md, package/etc/conf.d/conflib/syslog/app-syslog-fortigate_fortiweb.conf, package/lite/etc/addons/fortinet/app-syslog-fortigate_fortiweb.conf
fixes https://github.com/splunk/splunk-connect-for-syslog/issues/2353
=> docs: fix FortiWMail docs

docs/gettingstarted/index.md
Please review to make sure i didn't accidentally misinterpret the meaning, and then I'll d a final pass.
=> docs: update index.md

docs/gettingstarted/podman-systemd-general.md
incorporated Maciek's comments from previous PR
=> docs: update podman-systemd-general.md

docs/performance.md
=> docs: update performance.md

docs/lite.md
=> docs: update lite.md

docs/configuration.md, docs/experiments.md
Adding new Documentation for Parallelize feature, it will help in single TCP traffic to decongest.
=> docs: new document for Parallelize

package/etc/conf.d/log_paths/2/lp_dest_alts_global/plugin.jinja, package/etc/conf.d/log_paths/2/lp_dest_alts_global/plugin.py, package/etc/conf.d/sources/source_syslog/plugin.jinja, package/etc/conf.d/sources/source_syslog/plugin.py
Parallelize feature is moved to source block in place of log_paths
=> fix: parallelize feature is moved to source block

docs/sources/vendor/Aruba/silverpeak.md, package/etc/conf.d/conflib/netsource/app-netsource-aruba_silverpeak.conf, package/etc/test_parsers/app-vps-test-aruba_silverpeak.conf, package/lite/etc/addons/aruba/app-netsource-aruba_silverpeak.conf, tests/test_aruba.py, tests/test_aruba_silverpeak.py
Add a parser for Aruba SilverPeak requested in #2529
=> feat: add aruba silverpeak parser

docs/configuration.md, package/etc/conf.d/sources/source_syslog/plugin.jinja, package/etc/conf.d/sources/source_syslog/plugin.py
Added a env variable to provide provision of setting value of source field to 'sc4s'
=> feat: Added an env variable to set source as 'sc4s'

docs/sources/vendor/Dell/avamar.md
=> Docs: Update avamar.md

docs/architecture/lb/f5.md
Looks really good, i just made some tweaks to align it more closely with our style guide.
=> Docs review of f5.md

docs/sources/vendor/PaloaltoNetworks/panos.md
Updated the splunk add-on link in the PaloaltoNetworks panos documentation
=> docs: Updated the splunk add-on link in the panos documentation

package/enterprise/etc/conf.d/conflib/netsource/app-netsource-netapp_ontap.conf, package/enterprise/etc/conf.d/conflib/syslog/app-syslog-vectra_json.conf
Added a couple of parsers in the enterprise version.
=> fix: Added a couple of parsers in the enterprise version.

docs/sources/vendor/ISC/dhcpd.md
docs: Updated the sourcetype in the documentation of isc_dhcpd
=> docs: Updated the sourcetype in the documentation of isc_dhcpd

docs/sources/vendor/Dell/emc_powerstore.md, package/enterprise/etc/conf.d/conflib/syslog/app-syslog-dell_powerstore.conf, package/etc/conf.d/conflib/syslog/app-syslog-dell_powerstore.conf, package/lite/etc/addons/dell/app-syslog-dell_powerstore.conf, package/sbin/entrypoint.sh
Adds `SC4S_OPTION_DELL_POWERSTORE_INDEX` for backward compatibility with changes index
=> fix: add powerstore index var

package/Dockerfile, package/Dockerfile.enterprise, package/Dockerfile.lite, package/enterprise/etc/conf.d/log_paths/2/lp_dest_alts_global/plugin.py, package/enterprise/etc/conf.d/sources/source_syslog/plugin.py, package/enterprise/etc/pylib/parser_cef.py, package/enterprise/etc/pylib/parser_fix_dns.py, package/enterprise/etc/pylib/parser_kvqf.py, package/enterprise/etc/pylib/parser_leef.py, package/enterprise/etc/pylib/parser_stealthbits.py, package/enterprise/etc/pylib/parser_vps_cache.py, package/etc/pylib/parser_cef.py, package/etc/pylib/parser_kvqf.py, package/etc/pylib/parser_stealthbits.py
Added fixes for sonarqube issues.
Not sure why but most of them were already present in package/etc but not in package/enterprise/etc, so I guess some of that is a mixup when copying old version of the files there.
=> Fixed sonarqube issues
